# Generated by Django 4.2.11 on 2025-11-10 21:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_add_four_eyes_approval_to_transactions'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('items', models.JSONField(blank=True, default=list, help_text='List of cart items with product_id, variant_id, quantity, price')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Cart subtotal (sum of item prices)', max_digits=10)),
                ('conversation', models.OneToOneField(help_text='Conversation this cart belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='messaging.conversation')),
            ],
            options={
                'db_table': 'carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('currency', models.CharField(help_text='Currency code (ISO 4217)', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Order subtotal (sum of item prices)', max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total order amount (subtotal + shipping)', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], db_index=True, default='draft', help_text='Order status', max_length=20)),
                ('items', models.JSONField(default=list, help_text='Order items with product_id, variant_id, quantity, price')),
                ('payment_ref', models.CharField(blank=True, db_index=True, help_text='External payment reference ID', max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was received', null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='Timestamp when order was fulfilled', null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping tracking number', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional order metadata')),
                ('customer', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.customer')),
                ('tenant', models.ForeignKey(help_text='Tenant this order belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.tenant')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'customer', 'status'], name='orders_tenant__d0ddeb_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='orders_tenant__60bf39_idx'), models.Index(fields=['payment_ref'], name='orders_payment_386695_idx')],
            },
        ),
    ]
