# Generated by Django 4.2.16 on 2025-12-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('messaging', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this order belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cart',
            name='conversation',
            field=models.OneToOneField(help_text='Conversation this cart belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='messaging.conversation'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='orders_tenant__d0ddeb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='orders_tenant__60bf39_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_ref'], name='orders_payment_386695_idx'),
        ),
    ]
