# Generated by Django 4.2.11 on 2025-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('placed', 'Placed'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], db_index=True, default='draft', help_text='Order status', max_length=20),
        ),
    ]
