# Generated by Django 4.2.7 on 2025-12-22 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CampaignButtonInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "button_id",
                    models.CharField(
                        help_text="ID of the button that was clicked", max_length=100
                    ),
                ),
                (
                    "button_title",
                    models.CharField(
                        help_text="Title/text of the button", max_length=100
                    ),
                ),
                (
                    "button_type",
                    models.CharField(
                        choices=[
                            ("reply", "Reply Button"),
                            ("url", "URL Button"),
                            ("call", "Call Button"),
                        ],
                        help_text="Type of button clicked",
                        max_length=20,
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when button was clicked",
                    ),
                ),
                (
                    "led_to_conversion",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this interaction led to a conversion (order/booking)",
                    ),
                ),
                (
                    "conversion_type",
                    models.CharField(
                        blank=True,
                        choices=[("order", "Order"), ("appointment", "Appointment")],
                        help_text="Type of conversion if applicable",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "conversion_reference_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the order or appointment",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional interaction metadata",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_button_interactions",
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("transactional_messages", "Transactional Messages"),
                            ("reminder_messages", "Reminder Messages"),
                            ("promotional_messages", "Promotional Messages"),
                        ],
                        db_index=True,
                        help_text="Type of consent that changed",
                        max_length=30,
                    ),
                ),
                (
                    "previous_value",
                    models.BooleanField(help_text="Previous consent value"),
                ),
                ("new_value", models.BooleanField(help_text="New consent value")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("customer_initiated", "Customer Initiated"),
                            ("tenant_updated", "Tenant Updated"),
                            ("system_default", "System Default"),
                        ],
                        help_text="Source of the change",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the change (if provided)"
                    ),
                ),
            ],
            options={
                "db_table": "consent_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("bot", "Bot Handling"),
                            ("handoff", "Human Handoff"),
                            ("closed", "Closed"),
                            ("dormant", "Dormant"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Current conversation status",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("telegram", "Telegram"),
                            ("web", "Web Chat"),
                        ],
                        default="whatsapp",
                        help_text="Communication channel",
                        max_length=20,
                    ),
                ),
                (
                    "last_intent",
                    models.CharField(
                        blank=True,
                        help_text="Last detected intent",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "intent_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score of last intent",
                        null=True,
                    ),
                ),
                (
                    "low_confidence_count",
                    models.IntegerField(
                        default=0,
                        help_text="Count of consecutive low-confidence intents",
                    ),
                ),
                (
                    "handoff_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when handed off to human",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional conversation metadata",
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "transactional_messages",
                    models.BooleanField(
                        default=True,
                        help_text="Consent for transactional messages (order updates, payment confirmations)",
                    ),
                ),
                (
                    "reminder_messages",
                    models.BooleanField(
                        default=True,
                        help_text="Consent for reminder messages (appointment reminders, cart abandonment)",
                    ),
                ),
                (
                    "promotional_messages",
                    models.BooleanField(
                        default=False,
                        help_text="Consent for promotional messages (marketing, offers, campaigns)",
                    ),
                ),
                (
                    "last_updated_by",
                    models.CharField(
                        blank=True,
                        help_text="Source of last update (customer, tenant, system)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about preference changes (max 5,000 characters)",
                        max_length=5000,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer preferences",
                "db_table": "customer_preferences",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Inbound"), ("out", "Outbound")],
                        db_index=True,
                        help_text="Message direction",
                        max_length=3,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("customer_inbound", "Customer Inbound"),
                            ("bot_response", "Bot Response"),
                            ("automated_transactional", "Automated Transactional"),
                            ("automated_reminder", "Automated Reminder"),
                            ("automated_reengagement", "Automated Re-engagement"),
                            ("scheduled_promotional", "Scheduled Promotional"),
                            ("manual_outbound", "Manual Outbound"),
                        ],
                        db_index=True,
                        help_text="Type of message",
                        max_length=30,
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Message text content (max 10,000 characters)",
                        max_length=10000,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional message data (media URLs, buttons, etc.)",
                    ),
                ),
                (
                    "provider_msg_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Provider message ID (e.g., Twilio SID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "provider_status",
                    models.CharField(
                        blank=True,
                        help_text="Provider delivery status",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when message was sent",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when message was delivered",
                        null=True,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when message was read",
                        null=True,
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when message failed", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if delivery failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Campaign name for identification", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Campaign description and notes"
                    ),
                ),
                (
                    "message_content",
                    models.TextField(
                        help_text="Default message content to send (max 10,000 characters)",
                        max_length=10000,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Only"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        default="text",
                        help_text="Type of media included in campaign",
                        max_length=20,
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to media file (image, video, or document)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "media_caption",
                    models.TextField(
                        blank=True,
                        help_text="Caption for media (used with images, videos, documents)",
                    ),
                ),
                (
                    "buttons",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of button configurations (max 3): [{id, title, type}]",
                    ),
                ),
                (
                    "target_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Criteria for selecting recipients (tags, purchase_history, activity)",
                    ),
                ),
                (
                    "is_ab_test",
                    models.BooleanField(
                        default=False, help_text="Whether this campaign is an A/B test"
                    ),
                ),
                (
                    "variants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A/B test variants: [{name, content, customer_ids, metrics}]",
                    ),
                ),
                (
                    "delivery_count",
                    models.IntegerField(
                        default=0, help_text="Total customers targeted"
                    ),
                ),
                (
                    "delivered_count",
                    models.IntegerField(
                        default=0, help_text="Successfully delivered messages"
                    ),
                ),
                (
                    "failed_count",
                    models.IntegerField(
                        default=0, help_text="Failed delivery attempts"
                    ),
                ),
                (
                    "read_count",
                    models.IntegerField(
                        default=0, help_text="Messages read by customers"
                    ),
                ),
                (
                    "response_count",
                    models.IntegerField(
                        default=0, help_text="Customer responses received"
                    ),
                ),
                (
                    "conversion_count",
                    models.IntegerField(
                        default=0,
                        help_text="Conversions (orders/bookings) from campaign",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current campaign status",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When to execute this campaign",
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When campaign execution started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When campaign execution completed",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional campaign metadata",
                    ),
                ),
            ],
            options={
                "db_table": "message_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Current status of queued message",
                        max_length=20,
                    ),
                ),
                (
                    "queue_position",
                    models.IntegerField(
                        help_text="Position in queue (lower = earlier)"
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when message was queued",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when message was processed",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "message_queue",
                "ordering": ["conversation", "queue_position"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for identification", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Template content with {{placeholder}} syntax (max 5,000 characters)",
                        max_length=5000,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("reminder", "Reminder"),
                            ("promotional", "Promotional"),
                            ("reengagement", "Re-engagement"),
                        ],
                        help_text="Type of message this template is for",
                        max_length=20,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of available variables/placeholders",
                    ),
                ),
            ],
            options={
                "db_table": "message_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content to send (max 10,000 characters)",
                        max_length=10000,
                    ),
                ),
                (
                    "template_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Context data for template rendering",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, help_text="When to send this message"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of scheduled message",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Criteria for selecting recipients (for broadcast messages)",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        default="scheduled_promotional",
                        help_text="Type of message for consent checking",
                        max_length=30,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when message was actually sent",
                        null=True,
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when sending failed", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if sending failed",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (campaign_id, appointment_id, etc.)",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_messages",
                "ordering": ["scheduled_at"],
            },
        ),
    ]
