# Generated by Django 4.2.11 on 2025-11-10 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('bot', 'Bot Handling'), ('handoff', 'Human Handoff'), ('closed', 'Closed'), ('dormant', 'Dormant')], db_index=True, default='open', help_text='Current conversation status', max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('telegram', 'Telegram'), ('web', 'Web Chat')], default='whatsapp', help_text='Communication channel', max_length=20)),
                ('last_intent', models.CharField(blank=True, help_text='Last detected intent', max_length=100, null=True)),
                ('intent_confidence', models.FloatField(blank=True, help_text='Confidence score of last intent', null=True)),
                ('low_confidence_count', models.IntegerField(default=0, help_text='Count of consecutive low-confidence intents')),
                ('handoff_at', models.DateTimeField(blank=True, help_text='Timestamp when handed off to human', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional conversation metadata')),
                ('customer', models.ForeignKey(help_text='Customer in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.customer')),
                ('last_agent', models.ForeignKey(blank=True, help_text='Last human agent assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Template name for identification', max_length=255)),
                ('content', models.TextField(help_text='Template content with {{placeholder}} syntax')),
                ('message_type', models.CharField(choices=[('transactional', 'Transactional'), ('reminder', 'Reminder'), ('promotional', 'Promotional'), ('reengagement', 'Re-engagement')], help_text='Type of message this template is for', max_length=20)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of available variables/placeholders')),
                ('tenant', models.ForeignKey(help_text='Tenant this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='tenants.tenant')),
            ],
            options={
                'db_table': 'message_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], db_index=True, help_text='Message direction', max_length=3)),
                ('message_type', models.CharField(choices=[('customer_inbound', 'Customer Inbound'), ('bot_response', 'Bot Response'), ('automated_transactional', 'Automated Transactional'), ('automated_reminder', 'Automated Reminder'), ('automated_reengagement', 'Automated Re-engagement'), ('scheduled_promotional', 'Scheduled Promotional'), ('manual_outbound', 'Manual Outbound')], db_index=True, help_text='Type of message', max_length=30)),
                ('text', models.TextField(help_text='Message text content')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional message data (media URLs, buttons, etc.)')),
                ('provider_msg_id', models.CharField(blank=True, db_index=True, help_text='Provider message ID (e.g., Twilio SID)', max_length=255, null=True)),
                ('provider_status', models.CharField(blank=True, help_text='Provider delivery status', max_length=50, null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when message was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when message was delivered', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when message was read', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='Timestamp when message failed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', null=True)),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('template', models.ForeignKey(blank=True, help_text='Template used for this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetemplate')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['tenant', 'message_type'], name='message_tem_tenant__54e8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'direction', 'created_at'], name='messages_convers_274d78_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['provider_msg_id'], name='messages_provide_dbad94_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'created_at'], name='messages_message_b6f356_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='conversatio_tenant__cbd727_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'status', 'updated_at'], name='conversatio_tenant__625dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'updated_at'], name='conversatio_tenant__c2ee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'updated_at'], name='conversatio_status_bbfab5_idx'),
        ),
    ]
