# Generated by Django 4.2.11 on 2025-11-10 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_add_four_eyes_approval_to_transactions'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('transactional_messages', models.BooleanField(default=True, help_text='Consent for transactional messages (order updates, payment confirmations)')),
                ('reminder_messages', models.BooleanField(default=True, help_text='Consent for reminder messages (appointment reminders, cart abandonment)')),
                ('promotional_messages', models.BooleanField(default=False, help_text='Consent for promotional messages (marketing, offers, campaigns)')),
                ('last_updated_by', models.CharField(blank=True, help_text='Source of last update (customer, tenant, system)', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about preference changes')),
                ('customer', models.ForeignKey(help_text='Customer these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tenants.customer')),
                ('tenant', models.ForeignKey(help_text='Tenant this preference record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_preferences', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Customer preferences',
                'db_table': 'customer_preferences',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('consent_type', models.CharField(choices=[('transactional_messages', 'Transactional Messages'), ('reminder_messages', 'Reminder Messages'), ('promotional_messages', 'Promotional Messages')], db_index=True, help_text='Type of consent that changed', max_length=30)),
                ('previous_value', models.BooleanField(help_text='Previous consent value')),
                ('new_value', models.BooleanField(help_text='New consent value')),
                ('source', models.CharField(choices=[('customer_initiated', 'Customer Initiated'), ('tenant_updated', 'Tenant Updated'), ('system_default', 'System Default')], help_text='Source of the change', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the change (if provided)')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change (if tenant_updated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_changes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer this event is for', on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to='tenants.customer')),
                ('preferences', models.ForeignKey(help_text='Preferences record this event relates to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messaging.customerpreferences')),
                ('tenant', models.ForeignKey(help_text='Tenant this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'consent_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerpreferences',
            index=models.Index(fields=['tenant', 'customer'], name='customer_pr_tenant__d92829_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreferences',
            index=models.Index(fields=['tenant', 'promotional_messages'], name='customer_pr_tenant__edefca_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreferences',
            index=models.Index(fields=['tenant', 'reminder_messages'], name='customer_pr_tenant__bda299_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerpreferences',
            unique_together={('tenant', 'customer')},
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='consent_eve_tenant__6f601c_idx'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['tenant', 'consent_type', 'created_at'], name='consent_eve_tenant__e79521_idx'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['customer', 'created_at'], name='consent_eve_custome_6b26cb_idx'),
        ),
    ]
