# Generated by Django 4.2.16 on 2025-12-30 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Target customer (null for broadcast campaigns)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='tenants.customer'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Message record created when sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_from', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to='messaging.messagetemplate'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this scheduled message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this template belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='messagequeue',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation this queued message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='message_queue', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='messagequeue',
            name='message',
            field=models.ForeignKey(help_text='Message that is queued', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='messaging.messagetemplate'),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetemplate'),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='customer',
            field=models.ForeignKey(help_text='Customer these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tenants.customer'),
        ),
        migrations.AddField(
            model_name='customerpreferences',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this preference record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customer_preferences', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(help_text='Customer in this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.customer'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_agent',
            field=models.ForeignKey(blank=True, help_text='Last human agent assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made the change (if tenant_updated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='customer',
            field=models.ForeignKey(help_text='Customer this event is for', on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to='tenants.customer'),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='preferences',
            field=models.ForeignKey(help_text='Preferences record this event relates to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='messaging.customerpreferences'),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='campaignbuttoninteraction',
            name='campaign',
            field=models.ForeignKey(help_text='Campaign this interaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='button_interactions', to='messaging.messagecampaign'),
        ),
        migrations.AddField(
            model_name='campaignbuttoninteraction',
            name='customer',
            field=models.ForeignKey(help_text='Customer who clicked the button', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_button_interactions', to='tenants.customer'),
        ),
        migrations.AddField(
            model_name='campaignbuttoninteraction',
            name='message',
            field=models.ForeignKey(help_text='Campaign message that contained the button', on_delete=django.db.models.deletion.CASCADE, related_name='button_interactions', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='campaignbuttoninteraction',
            name='response_message',
            field=models.ForeignKey(blank=True, help_text="Customer's response message after clicking button", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_button', to='messaging.message'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['tenant', 'status', 'scheduled_at'], name='scheduled_m_tenant__b00130_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='scheduled_m_tenant__7d6006_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['status', 'scheduled_at'], name='scheduled_m_status_c4bde9_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['tenant', 'message_type'], name='message_tem_tenant__54e8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='messagequeue',
            index=models.Index(fields=['conversation', 'status', 'queue_position'], name='message_que_convers_3f6b58_idx'),
        ),
        migrations.AddIndex(
            model_name='messagequeue',
            index=models.Index(fields=['status', 'queued_at'], name='message_que_status_249332_idx'),
        ),
        migrations.AddIndex(
            model_name='messagequeue',
            index=models.Index(fields=['conversation', 'queued_at'], name='message_que_convers_1ab3ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagequeue',
            unique_together={('conversation', 'queue_position')},
        ),
        migrations.AddIndex(
            model_name='messagecampaign',
            index=models.Index(fields=['tenant', 'status'], name='message_cam_tenant__00287c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagecampaign',
            index=models.Index(fields=['tenant', 'created_at'], name='message_cam_tenant__9e1e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagecampaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='message_cam_status_13dfe3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'direction', 'created_at'], name='messages_convers_274d78_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['provider_msg_id'], name='messages_provide_dbad94_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'created_at'], name='messages_message_b6f356_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreferences',
            index=models.Index(fields=['tenant', 'customer'], name='customer_pr_tenant__d92829_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreferences',
            index=models.Index(fields=['tenant', 'promotional_messages'], name='customer_pr_tenant__edefca_idx'),
        ),
        migrations.AddIndex(
            model_name='customerpreferences',
            index=models.Index(fields=['tenant', 'reminder_messages'], name='customer_pr_tenant__bda299_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerpreferences',
            unique_together={('tenant', 'customer')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='conversatio_tenant__cbd727_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'status', 'updated_at'], name='conversatio_tenant__625dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'updated_at'], name='conversatio_tenant__c2ee7a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'updated_at'], name='conversatio_status_bbfab5_idx'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['tenant', 'customer', 'created_at'], name='consent_eve_tenant__6f601c_idx'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['tenant', 'consent_type', 'created_at'], name='consent_eve_tenant__e79521_idx'),
        ),
        migrations.AddIndex(
            model_name='consentevent',
            index=models.Index(fields=['customer', 'created_at'], name='consent_eve_custome_6b26cb_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignbuttoninteraction',
            index=models.Index(fields=['campaign', 'clicked_at'], name='campaign_bu_campaig_c33923_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignbuttoninteraction',
            index=models.Index(fields=['campaign', 'button_id'], name='campaign_bu_campaig_61c583_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignbuttoninteraction',
            index=models.Index(fields=['customer', 'clicked_at'], name='campaign_bu_custome_edea06_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignbuttoninteraction',
            index=models.Index(fields=['campaign', 'led_to_conversion'], name='campaign_bu_campaig_b5f633_idx'),
        ),
    ]
