# Generated by Django 4.2.11 on 2025-11-11 06:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_four_eyes_approval_to_transactions'),
        ('messaging', '0002_add_customer_preferences_and_consent_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('content', models.TextField(help_text='Message content to send')),
                ('template_context', models.JSONField(blank=True, default=dict, help_text='Context data for template rendering')),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When to send this message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', help_text='Current status of scheduled message', max_length=20)),
                ('recipient_criteria', models.JSONField(blank=True, default=dict, help_text='Criteria for selecting recipients (for broadcast messages)')),
                ('message_type', models.CharField(default='scheduled_promotional', help_text='Type of message for consent checking', max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when message was actually sent', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='Timestamp when sending failed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (campaign_id, appointment_id, etc.)')),
                ('customer', models.ForeignKey(blank=True, help_text='Target customer (null for broadcast campaigns)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='tenants.customer')),
                ('message', models.ForeignKey(blank=True, help_text='Message record created when sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_from', to='messaging.message')),
                ('template', models.ForeignKey(blank=True, help_text='Template used for this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to='messaging.messagetemplate')),
                ('tenant', models.ForeignKey(help_text='Tenant this scheduled message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scheduled_messages',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'scheduled_at'], name='scheduled_m_tenant__b00130_idx'), models.Index(fields=['tenant', 'customer', 'status'], name='scheduled_m_tenant__7d6006_idx'), models.Index(fields=['status', 'scheduled_at'], name='scheduled_m_status_c4bde9_idx')],
            },
        ),
    ]
