# Generated by Django 4.2.11 on 2025-11-11 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_four_eyes_approval_to_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_add_scheduled_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Campaign name for identification', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Campaign description and notes')),
                ('message_content', models.TextField(help_text='Default message content to send')),
                ('target_criteria', models.JSONField(blank=True, default=dict, help_text='Criteria for selecting recipients (tags, purchase_history, activity)')),
                ('is_ab_test', models.BooleanField(default=False, help_text='Whether this campaign is an A/B test')),
                ('variants', models.JSONField(blank=True, default=list, help_text='A/B test variants: [{name, content, customer_ids, metrics}]')),
                ('delivery_count', models.IntegerField(default=0, help_text='Total customers targeted')),
                ('delivered_count', models.IntegerField(default=0, help_text='Successfully delivered messages')),
                ('failed_count', models.IntegerField(default=0, help_text='Failed delivery attempts')),
                ('read_count', models.IntegerField(default=0, help_text='Messages read by customers')),
                ('response_count', models.IntegerField(default=0, help_text='Customer responses received')),
                ('conversion_count', models.IntegerField(default=0, help_text='Conversions (orders/bookings) from campaign')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', help_text='Current campaign status', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='When to execute this campaign', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When campaign execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When campaign execution completed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional campaign metadata')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='messaging.messagetemplate')),
                ('tenant', models.ForeignKey(help_text='Tenant this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant')),
            ],
            options={
                'db_table': 'message_campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='message_cam_tenant__00287c_idx'), models.Index(fields=['tenant', 'created_at'], name='message_cam_tenant__9e1e0a_idx'), models.Index(fields=['status', 'scheduled_at'], name='message_cam_status_13dfe3_idx')],
            },
        ),
    ]
