# Generated by Django 4.2.11 on 2025-11-15 02:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_add_message_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='queued', help_text='Current status of queued message', max_length=20)),
                ('queue_position', models.IntegerField(help_text='Position in queue (lower = earlier)')),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when message was queued')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when message was processed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('conversation', models.ForeignKey(help_text='Conversation this queued message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='message_queue', to='messaging.conversation')),
                ('message', models.ForeignKey(help_text='Message that is queued', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='messaging.message')),
            ],
            options={
                'db_table': 'message_queue',
                'ordering': ['conversation', 'queue_position'],
                'indexes': [models.Index(fields=['conversation', 'status', 'queue_position'], name='message_que_convers_3f6b58_idx'), models.Index(fields=['status', 'queued_at'], name='message_que_status_249332_idx'), models.Index(fields=['conversation', 'queued_at'], name='message_que_convers_1ab3ab_idx')],
                'unique_together': {('conversation', 'queue_position')},
            },
        ),
    ]
