# Generated by Django 4.2.11 on 2025-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_add_message_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecampaign',
            name='buttons',
            field=models.JSONField(blank=True, default=list, help_text='List of button configurations (max 3): [{id, title, type}]'),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='media_caption',
            field=models.TextField(blank=True, help_text='Caption for media (used with images, videos, documents)'),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='media_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', help_text='Type of media included in campaign', max_length=20),
        ),
        migrations.AddField(
            model_name='messagecampaign',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL to media file (image, video, or document)', max_length=500, null=True),
        ),
    ]
