# Generated by Django 4.2.11 on 2025-11-15 04:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_add_together_ai_configuration'),
        ('messaging', '0006_add_rich_media_to_campaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignButtonInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('button_id', models.CharField(help_text='ID of the button that was clicked', max_length=100)),
                ('button_title', models.CharField(help_text='Title/text of the button', max_length=100)),
                ('button_type', models.CharField(choices=[('reply', 'Reply Button'), ('url', 'URL Button'), ('call', 'Call Button')], help_text='Type of button clicked', max_length=20)),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when button was clicked')),
                ('led_to_conversion', models.BooleanField(default=False, help_text='Whether this interaction led to a conversion (order/booking)')),
                ('conversion_type', models.CharField(blank=True, choices=[('order', 'Order'), ('appointment', 'Appointment')], help_text='Type of conversion if applicable', max_length=20, null=True)),
                ('conversion_reference_id', models.UUIDField(blank=True, help_text='ID of the order or appointment', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional interaction metadata')),
                ('campaign', models.ForeignKey(help_text='Campaign this interaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='button_interactions', to='messaging.messagecampaign')),
                ('customer', models.ForeignKey(help_text='Customer who clicked the button', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_button_interactions', to='tenants.customer')),
                ('message', models.ForeignKey(help_text='Campaign message that contained the button', on_delete=django.db.models.deletion.CASCADE, related_name='button_interactions', to='messaging.message')),
                ('response_message', models.ForeignKey(blank=True, help_text="Customer's response message after clicking button", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_button', to='messaging.message')),
            ],
            options={
                'db_table': 'campaign_button_interactions',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['campaign', 'clicked_at'], name='campaign_bu_campaig_c33923_idx'), models.Index(fields=['campaign', 'button_id'], name='campaign_bu_campaig_61c583_idx'), models.Index(fields=['customer', 'clicked_at'], name='campaign_bu_custome_edea06_idx'), models.Index(fields=['campaign', 'led_to_conversion'], name='campaign_bu_campaig_b5f633_idx')],
            },
        ),
    ]
