# Generated by Django 4.2.11 on 2025-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_campaign_button_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpreferences',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about preference changes (max 5,000 characters)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='Message text content (max 10,000 characters)', max_length=10000),
        ),
        migrations.AlterField(
            model_name='messagecampaign',
            name='message_content',
            field=models.TextField(help_text='Default message content to send (max 10,000 characters)', max_length=10000),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(help_text='Template content with {{placeholder}} syntax (max 5,000 characters)', max_length=5000),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='content',
            field=models.TextField(help_text='Message content to send (max 10,000 characters)', max_length=10000),
        ),
    ]
