# Generated by Django 4.2.11 on 2025-11-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='conv_tenant_status_upd_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='msg_conv_created_dir_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='msg_conv_type_created_idx',
        ),
    ]
