# Generated by Django 4.2.7 on 2025-12-22 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                ("title", models.CharField(help_text="Service title", max_length=500)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Service description", null=True
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base price (can be overridden by variants)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether service is active and bookable",
                    ),
                ),
                (
                    "requires_slot",
                    models.BooleanField(
                        default=True,
                        help_text="Whether service requires time slot booking",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional service metadata",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this service belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Variant title (e.g., '30-minute session')",
                        max_length=255,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Duration in minutes"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Variant price (overrides service base_price if set)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "attrs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom attributes (e.g., {'level': 'premium', 'therapist': 'senior'})",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service this variant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "db_table": "service_variants",
                "ordering": ["duration_minutes", "price"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of week (0=Monday, 6=Sunday) for recurring availability",
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Specific date for one-time availability",
                        null=True,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Start time of availability window"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="End time of availability window"),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        default=1, help_text="Number of concurrent appointments allowed"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="Timezone for this availability window", max_length=50
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service this availability window applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_windows",
                        to="services.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this availability window belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_windows",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "availability_windows",
                "ordering": ["weekday", "date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "start_dt",
                    models.DateTimeField(
                        db_index=True, help_text="Appointment start date and time"
                    ),
                ),
                (
                    "end_dt",
                    models.DateTimeField(
                        db_index=True, help_text="Appointment end date and time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("done", "Done"),
                            ("canceled", "Canceled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current appointment status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Customer notes or special requests",
                        null=True,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True,
                        help_text="External calendar or booking system reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional appointment metadata",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who booked the appointment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="tenants.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service being booked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="services.service",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this appointment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific service variant (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="services.servicevariant",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["start_dt"],
            },
        ),
        migrations.AddIndex(
            model_name="servicevariant",
            index=models.Index(
                fields=["service", "duration_minutes"],
                name="service_var_service_7568cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["tenant", "is_active"], name="services_tenant__aacd0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["tenant", "title"], name="services_tenant__52fb87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["tenant", "created_at"], name="services_tenant__43974a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availabilitywindow",
            index=models.Index(
                fields=["tenant", "service", "weekday"],
                name="availabilit_tenant__f37d0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="availabilitywindow",
            index=models.Index(
                fields=["tenant", "service", "date"],
                name="availabilit_tenant__3802c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="availabilitywindow",
            index=models.Index(
                fields=["service", "weekday"], name="availabilit_service_e075e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availabilitywindow",
            index=models.Index(
                fields=["service", "date"], name="availabilit_service_8d6e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["tenant", "customer", "status"],
                name="appointment_tenant__e72c30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["tenant", "service", "start_dt"],
                name="appointment_tenant__615e2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["tenant", "start_dt", "status"],
                name="appointment_tenant__c55338_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["service", "start_dt", "status"],
                name="appointment_service_5150bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["customer", "start_dt"], name="appointment_custome_da4aa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "start_dt"], name="appointment_status_bfe13d_idx"
            ),
        ),
    ]
