# Generated by Django 4.2.7 on 2025-12-22 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("woocommerce", "WooCommerce"),
                            ("shopify", "Shopify"),
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Webhook provider/source",
                        max_length=50,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        db_index=True,
                        help_text="Event type or webhook action",
                        max_length=100,
                    ),
                ),
                ("payload", models.JSONField(help_text="Full webhook request payload")),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Request headers (excluding sensitive data)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("unauthorized", "Unauthorized"),
                            ("subscription_inactive", "Subscription Inactive"),
                        ],
                        db_index=True,
                        help_text="Processing status",
                        max_length=30,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True,
                        help_text="Full error traceback for debugging",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when webhook was received",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when processing completed",
                        null=True,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Processing time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Source IP address of webhook request",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent from webhook request",
                        null=True,
                    ),
                ),
                (
                    "request_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Request ID for tracing",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "webhook_logs",
                "ordering": ["-received_at"],
            },
        ),
    ]
