# Generated by Django 4.2.16 on 2025-12-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this webhook is associated with (null if resolution failed)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['tenant', 'received_at'], name='webhook_log_tenant__784ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['provider', 'status', 'received_at'], name='webhook_log_provide_59939e_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['status', 'received_at'], name='webhook_log_status_92de8b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['event', 'received_at'], name='webhook_log_event_1e47a5_idx'),
        ),
    ]
