# Generated by Django 4.2.16 on 2025-12-30 08:16

import apps.core.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('key', models.CharField(db_index=True, help_text="Setting key (e.g., 'email_provider', 'sendgrid_api_key')", max_length=100, unique=True)),
                ('value', models.TextField(help_text="Setting value (will be encrypted if setting_type is 'encrypted')")),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('encrypted', 'Encrypted String'), ('json', 'JSON Object')], default='string', help_text='Data type of the setting value', max_length=20)),
                ('category', models.CharField(choices=[('email', 'Email Service'), ('sms', 'SMS Service'), ('ai', 'AI Provider'), ('payment', 'Payment Settings'), ('security', 'Security'), ('general', 'General')], default='general', help_text='Setting category for organization', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Whether this setting contains sensitive data (API keys, passwords)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
            ],
            options={
                'db_table': 'platform_settings',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['key'], name='platform_se_key_ac184b_idx'), models.Index(fields=['category', 'is_active'], name='platform_se_categor_6d4ae6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformPaymentCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('stripe', 'Stripe'), ('paystack', 'Paystack'), ('pesapal', 'Pesapal')], help_text='Payment provider name', max_length=20)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox/Test'), ('production', 'Production')], default='sandbox', help_text='Environment (sandbox or production)', max_length=20)),
                ('api_key', apps.core.fields.EncryptedCharField(blank=True, help_text='Primary API key or consumer key', max_length=500)),
                ('api_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='API secret or consumer secret', max_length=500)),
                ('additional_config', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific configuration (shortcode, passkey, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these credentials are currently active')),
                ('description', models.TextField(blank=True, help_text='Description or notes about these credentials')),
            ],
            options={
                'db_table': 'platform_payment_credentials',
                'ordering': ['provider', 'environment'],
                'indexes': [models.Index(fields=['provider', 'environment', 'is_active'], name='platform_pa_provide_89652d_idx')],
                'unique_together': {('provider', 'environment')},
            },
        ),
    ]
