# Generated by Django 4.2.11 on 2025-11-10 08:40

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('phone_e164', apps.core.fields.EncryptedCharField(db_index=True, help_text='Encrypted phone number in E.164 format', max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Global Party',
                'verbose_name_plural': 'Global Parties',
                'db_table': 'global_parties',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Tier name (Starter, Growth, Enterprise)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Tier description')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly subscription price', max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, help_text='Yearly subscription price (typically 20% off)', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('monthly_messages', models.IntegerField(blank=True, help_text='Maximum outbound messages per month (null = unlimited)', null=True)),
                ('max_products', models.IntegerField(blank=True, help_text='Maximum products in catalog (null = unlimited)', null=True)),
                ('max_services', models.IntegerField(blank=True, help_text='Maximum bookable services (null = unlimited)', null=True)),
                ('max_campaign_sends', models.IntegerField(blank=True, help_text='Maximum campaign sends per month (null = unlimited)', null=True)),
                ('max_daily_outbound', models.IntegerField(blank=True, help_text='Maximum daily outbound messages (null = unlimited)', null=True)),
                ('payment_facilitation', models.BooleanField(default=False, help_text='Enable payment processing and wallet')),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Transaction fee percentage for facilitated payments', max_digits=5)),
                ('ab_test_variants', models.IntegerField(default=2, help_text='Maximum A/B test variants allowed')),
                ('priority_support', models.BooleanField(default=False, help_text='Priority customer support')),
                ('custom_branding', models.BooleanField(default=False, help_text='Custom branding and templates')),
                ('api_access', models.CharField(choices=[('none', 'No API Access'), ('read', 'Read-Only API'), ('full', 'Full API Access')], default='read', help_text='API access level', max_length=10)),
            ],
            options={
                'db_table': 'subscription_tiers',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Business name', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Free Trial'), ('trial_expired', 'Trial Expired'), ('suspended', 'Suspended'), ('canceled', 'Canceled')], db_index=True, default='trial', help_text='Current tenant status', max_length=20)),
                ('subscription_waived', models.BooleanField(default=False, help_text='Whether subscription fees are waived')),
                ('trial_start_date', models.DateTimeField(blank=True, help_text='Free trial start date', null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, db_index=True, help_text='Free trial end date', null=True)),
                ('whatsapp_number', models.CharField(db_index=True, help_text='WhatsApp business number (E.164 format)', max_length=20, unique=True)),
                ('twilio_sid', apps.core.fields.EncryptedCharField(help_text='Encrypted Twilio Account SID', max_length=500)),
                ('twilio_token', apps.core.fields.EncryptedCharField(help_text='Encrypted Twilio Auth Token', max_length=500)),
                ('webhook_secret', apps.core.fields.EncryptedCharField(help_text='Encrypted webhook signature secret', max_length=500)),
                ('api_keys', models.JSONField(blank=True, default=list, help_text='List of API key hashes with metadata: [{key_hash, name, created_at}]')),
                ('allowed_origins', models.JSONField(blank=True, default=list, help_text='CORS allowed origins for this tenant')),
                ('timezone', models.CharField(default='UTC', help_text='Tenant timezone for scheduling', max_length=50)),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Start of quiet hours (no automated messages)')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='End of quiet hours')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for notifications', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=20, null=True)),
                ('subscription_tier', models.ForeignKey(blank=True, help_text='Current subscription tier', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.subscriptiontier')),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('phone_e164', apps.core.fields.EncryptedCharField(db_index=True, help_text='Encrypted phone number in E.164 format', max_length=500)),
                ('name', models.CharField(blank=True, help_text='Customer name (if provided)', max_length=255, null=True)),
                ('timezone', models.CharField(blank=True, help_text='Customer timezone (detected or provided)', max_length=50, null=True)),
                ('language', models.CharField(blank=True, help_text='Preferred language code', max_length=10, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Customer tags for segmentation (e.g., ['vip', 'new_customer'])")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional customer metadata')),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Last interaction timestamp', null=True)),
                ('first_interaction_at', models.DateTimeField(blank=True, help_text='First interaction timestamp', null=True)),
                ('global_party', models.ForeignKey(blank=True, help_text='Internal linkage across tenants (not exposed via API)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tenants.globalparty')),
                ('tenant', models.ForeignKey(help_text='Tenant this customer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', 'created_at'], name='tenants_status_6a2fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['trial_end_date'], name='tenants_trial_e_19bb02_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'phone_e164'], name='customers_tenant__7f9c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'last_seen_at'], name='customers_tenant__b46ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'created_at'], name='customers_tenant__bac0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['global_party'], name='customers_global__03ed1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'phone_e164')},
        ),
    ]
