# Generated by Django 4.2.7 on 2025-12-22 12:58

import apps.core.fields
import apps.tenants.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalParty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "phone_e164",
                    apps.core.fields.EncryptedCharField(
                        db_index=True,
                        help_text="Encrypted phone number in E.164 format",
                        max_length=500,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Party",
                "verbose_name_plural": "Global Parties",
                "db_table": "global_parties",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        help_text="Billing frequency",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current subscription status",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Subscription start date")),
                (
                    "next_billing_date",
                    models.DateField(db_index=True, help_text="Next billing date"),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, help_text="Cancellation timestamp", null=True
                    ),
                ),
                (
                    "payment_method_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment method identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tier name (Starter, Growth, Enterprise)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Tier description"),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription price",
                        max_digits=10,
                    ),
                ),
                (
                    "yearly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Yearly subscription price (typically 20% off)",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "monthly_messages",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum outbound messages per month (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_products",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum products in catalog (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_services",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum bookable services (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_campaign_sends",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum campaign sends per month (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_daily_outbound",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum daily outbound messages (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "payment_facilitation",
                    models.BooleanField(
                        default=False, help_text="Enable payment processing and wallet"
                    ),
                ),
                (
                    "transaction_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Transaction fee percentage for facilitated payments",
                        max_digits=5,
                    ),
                ),
                (
                    "ab_test_variants",
                    models.IntegerField(
                        default=2, help_text="Maximum A/B test variants allowed"
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(
                        default=False, help_text="Priority customer support"
                    ),
                ),
                (
                    "custom_branding",
                    models.BooleanField(
                        default=False, help_text="Custom branding and templates"
                    ),
                ),
                (
                    "api_access",
                    models.CharField(
                        choices=[
                            ("none", "No API Access"),
                            ("read", "Read-Only API"),
                            ("full", "Full API Access"),
                        ],
                        default="read",
                        help_text="API access level",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "subscription_tiers",
                "ordering": ["monthly_price"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Business name", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Free Trial"),
                            ("trial_expired", "Trial Expired"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="trial",
                        help_text="Current tenant status",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_waived",
                    models.BooleanField(
                        default=False, help_text="Whether subscription fees are waived"
                    ),
                ),
                (
                    "trial_start_date",
                    models.DateTimeField(
                        blank=True, help_text="Free trial start date", null=True
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Free trial end date",
                        null=True,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        db_index=True,
                        help_text="WhatsApp business number (E.164 format)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "api_keys",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of API key hashes with metadata: [{key_hash, name, created_at}]",
                    ),
                ),
                (
                    "allowed_origins",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="CORS allowed origins for this tenant",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Tenant timezone for scheduling",
                        max_length=50,
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        default="22:00",
                        help_text="Start of quiet hours (no automated messages)",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(default="08:00", help_text="End of quiet hours"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email for notifications",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        default="Assistant",
                        help_text="Custom bot name for conversations",
                        max_length=100,
                    ),
                ),
                (
                    "tone_style",
                    models.CharField(
                        choices=[
                            ("friendly_concise", "Friendly & Concise"),
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("formal", "Formal"),
                        ],
                        default="friendly_concise",
                        help_text="Communication tone and style",
                        max_length=50,
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("sw", "Swahili"),
                            ("sheng", "Sheng"),
                        ],
                        default="en",
                        help_text="Default language for conversations",
                        max_length=10,
                    ),
                ),
                (
                    "allowed_languages",
                    models.JSONField(
                        blank=True,
                        default=apps.tenants.models.default_allowed_languages,
                        help_text="Languages allowed for this tenant (e.g., ['en', 'sw', 'sheng'])",
                    ),
                ),
                (
                    "max_chattiness_level",
                    models.IntegerField(
                        choices=[
                            (0, "Strictly Business"),
                            (1, "Minimal Friendliness"),
                            (2, "Friendly but Bounded"),
                            (3, "More Friendly"),
                        ],
                        default=2,
                        help_text="Maximum chattiness level for cost control (0-3)",
                    ),
                ),
                (
                    "payment_methods_enabled",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enabled payment methods: {'mpesa_stk': True, 'mpesa_c2b': True, 'pesapal_card': False}",
                    ),
                ),
                (
                    "escalation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Human escalation rules and triggers configuration",
                    ),
                ),
                (
                    "subscription_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current subscription tier",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="tenants.subscriptiontier",
                    ),
                ),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current wallet balance",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="Currency code", max_length=3
                    ),
                ),
                (
                    "minimum_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Minimum withdrawal amount",
                        max_digits=10,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Tenant this wallet belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_wallets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("customer_payment", "Customer Payment"),
                            ("platform_fee", "Platform Fee"),
                            ("withdrawal", "Withdrawal"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        db_index=True,
                        help_text="Type of transaction",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (gross)",
                        max_digits=12,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform fee (for customer_payment type)",
                        max_digits=12,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount after fees",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Transaction status",
                        max_length=20,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related entity (e.g., 'order', 'appointment')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True, help_text="ID of related entity", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction metadata",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the transaction"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved the transaction (for four-eyes approval)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the transaction (for four-eyes approval)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet this transaction affects",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="tenants.tenantwallet",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "twilio_sid",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted Twilio Account SID",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "twilio_token",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted Twilio Auth Token",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "twilio_webhook_secret",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted Twilio webhook signature secret",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "woo_store_url",
                    models.URLField(
                        blank=True, help_text="WooCommerce store URL", null=True
                    ),
                ),
                (
                    "woo_consumer_key",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted WooCommerce consumer key",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "woo_consumer_secret",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted WooCommerce consumer secret",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "woo_webhook_secret",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted WooCommerce webhook secret",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "shopify_shop_domain",
                    models.CharField(
                        blank=True,
                        help_text="Shopify shop domain (e.g., mystore.myshopify.com)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "shopify_access_token",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted Shopify Admin API access token",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "shopify_webhook_secret",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted Shopify webhook secret",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "whatsapp_business_id",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted WhatsApp Business Account ID",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "whatsapp_access_token",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted WhatsApp Business API access token",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "openai_api_key",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted OpenAI API key",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "openai_org_id",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted OpenAI organization ID",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "together_api_key",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted Together AI API key",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "gemini_api_key",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted Google Gemini API key",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        default="openai",
                        help_text="LLM provider to use (openai, together, gemini, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "llm_timeout",
                    models.FloatField(
                        blank=True,
                        help_text="Timeout in seconds for LLM API calls",
                        null=True,
                    ),
                ),
                (
                    "llm_max_retries",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of retries for LLM API calls",
                        null=True,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe customer ID for this tenant",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stripe_payment_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Stripe PaymentMethod IDs: [{id, last4, brand, exp_month, exp_year, is_default}]",
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("mobile_money", "Mobile Money"),
                            ("paypal", "PayPal"),
                        ],
                        help_text="Payout method for tenant earnings",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payout_details",
                    apps.core.fields.EncryptedTextField(
                        blank=True,
                        help_text="Encrypted JSON with payout account details",
                        null=True,
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Notification preferences by channel and event type",
                    ),
                ),
                (
                    "business_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Business hours by day of week",
                    ),
                ),
                (
                    "integrations_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Status and metadata for each integration",
                    ),
                ),
                (
                    "branding",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Branding and customization settings",
                    ),
                ),
                (
                    "compliance_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GDPR, data retention, and legal compliance settings",
                    ),
                ),
                (
                    "onboarding_status",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Onboarding step completion status with timestamps",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether all required onboarding steps are complete",
                    ),
                ),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When onboarding was completed", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional settings metadata (payment provider credentials, etc.)",
                    ),
                ),
                (
                    "feature_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature flags for gradual rollout and A/B testing",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        help_text="Associated tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Settings",
                "verbose_name_plural": "Tenant Settings",
                "db_table": "tenant_settings",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("tier_changed", "Tier Changed"),
                            ("renewed", "Renewed"),
                            ("suspended", "Suspended"),
                            ("canceled", "Canceled"),
                            ("reactivated", "Reactivated"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_succeeded", "Payment Succeeded"),
                        ],
                        db_index=True,
                        help_text="Type of event",
                        max_length=30,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event metadata (e.g., previous_tier, new_tier, reason)",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="Subscription this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tenants.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        help_text="Type of discount",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount value (percentage or fixed amount)",
                        max_digits=10,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Discount expiry date (null = no expiry)",
                        null=True,
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times discount can be applied (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of times discount has been applied"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional discount code",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Discount description"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this discount applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_discounts",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="tenant",
            field=models.OneToOneField(
                help_text="Tenant this subscription belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tier",
            field=models.ForeignKey(
                help_text="Subscription tier",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="tenants.subscriptiontier",
            ),
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "phone_e164",
                    apps.core.fields.EncryptedCharField(
                        db_index=True,
                        help_text="Encrypted phone number in E.164 format",
                        max_length=500,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Customer name (if provided)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="Customer timezone (detected or provided)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Preferred language code",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Customer tags for segmentation (e.g., ['vip', 'new_customer'])",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional customer metadata",
                    ),
                ),
                (
                    "payment_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Customer payment preferences: {preferred_provider, saved_methods: [{provider, details}]}",
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("sw", "Swahili"),
                            ("sheng", "Sheng"),
                            ("mixed", "Mixed"),
                        ],
                        help_text="Customer's preferred language for conversations",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "marketing_opt_in",
                    models.BooleanField(
                        blank=True,
                        help_text="Customer consent for marketing communications (null=not set, True=opted in, False=opted out)",
                        null=True,
                    ),
                ),
                (
                    "consent_flags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed consent flags: {'marketing': True/False, 'notifications': True/False, 'data_processing': True/False}",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Last interaction timestamp",
                        null=True,
                    ),
                ),
                (
                    "first_interaction_at",
                    models.DateTimeField(
                        blank=True, help_text="First interaction timestamp", null=True
                    ),
                ),
                (
                    "global_party",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal linkage across tenants (not exposed via API)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="tenants.globalparty",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this customer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "customers",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "previous_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Balance before transaction",
                        max_digits=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of change (positive for credit, negative for debit)",
                        max_digits=12,
                    ),
                ),
                (
                    "new_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Balance after transaction",
                        max_digits=12,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Transaction that caused this balance change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_records",
                        to="tenants.transaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="Wallet this audit record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_records",
                        to="tenants.tenantwallet",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_audits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="wallet_audi_wallet__b9963d_idx",
                    ),
                    models.Index(
                        fields=["transaction"], name="wallet_audi_transac_1375b2_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tenant", "transaction_type", "created_at"],
                name="transaction_tenant__f1f6a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["wallet", "status"], name="transaction_wallet__127b5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type", "status", "created_at"],
                name="transaction_transac_375222_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference_type", "reference_id"],
                name="transaction_referen_c8c45f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["status", "created_at"], name="tenants_status_6a2fc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["trial_end_date"], name="tenants_trial_e_19bb02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionevent",
            index=models.Index(
                fields=["subscription", "created_at"],
                name="subscriptio_subscri_462480_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="subscriptio_event_t_6825a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptiondiscount",
            index=models.Index(
                fields=["tenant", "expiry_date"], name="subscriptio_tenant__3ea621_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["status", "next_billing_date"],
                name="subscriptio_status_5e41b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["tenant", "status"], name="subscriptio_tenant__5476fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "phone_e164"], name="customers_tenant__7f9c3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "last_seen_at"], name="customers_tenant__b46ae4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "created_at"], name="customers_tenant__bac0f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["global_party"], name="customers_global__03ed1c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("tenant", "phone_e164")},
        ),
    ]
