# Generated by Django 4.2.11 on 2025-11-10 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing frequency', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='active', help_text='Current subscription status', max_length=20)),
                ('start_date', models.DateField(help_text='Subscription start date')),
                ('next_billing_date', models.DateField(db_index=True, help_text='Next billing date')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='Cancellation timestamp', null=True)),
                ('payment_method_id', models.CharField(blank=True, help_text='External payment method identifier', max_length=255, null=True)),
                ('tenant', models.OneToOneField(help_text='Tenant this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
                ('tier', models.ForeignKey(help_text='Subscription tier', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.subscriptiontier')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('tier_changed', 'Tier Changed'), ('renewed', 'Renewed'), ('suspended', 'Suspended'), ('canceled', 'Canceled'), ('reactivated', 'Reactivated'), ('payment_failed', 'Payment Failed'), ('payment_succeeded', 'Payment Succeeded')], db_index=True, help_text='Type of event', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Event metadata (e.g., previous_tier, new_tier, reason)')),
                ('subscription', models.ForeignKey(help_text='Subscription this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tenants.subscription')),
            ],
            options={
                'db_table': 'subscription_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', 'created_at'], name='subscriptio_subscri_462480_idx'), models.Index(fields=['event_type', 'created_at'], name='subscriptio_event_t_6825a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], help_text='Type of discount', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10)),
                ('expiry_date', models.DateField(blank=True, help_text='Discount expiry date (null = no expiry)', null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum number of times discount can be applied (null = unlimited)', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times discount has been applied')),
                ('code', models.CharField(blank=True, help_text='Optional discount code', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Discount description')),
                ('tenant', models.ForeignKey(help_text='Tenant this discount applies to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_discounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subscription_discounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'expiry_date'], name='subscriptio_tenant__3ea621_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'next_billing_date'], name='subscriptio_status_5e41b4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'status'], name='subscriptio_tenant__5476fe_idx'),
        ),
    ]
