# Generated by Django 4.2.11 on 2025-11-10 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_subscription_subscriptionevent_subscriptiondiscount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Current wallet balance', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, default=10, help_text='Minimum withdrawal amount', max_digits=10)),
                ('tenant', models.OneToOneField(help_text='Tenant this wallet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('transaction_type', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('platform_fee', 'Platform Fee'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], db_index=True, help_text='Type of transaction', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (gross)', max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (for customer_payment type)', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount after fees', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', help_text='Transaction status', max_length=20)),
                ('reference_type', models.CharField(blank=True, help_text="Type of related entity (e.g., 'order', 'appointment')", max_length=50, null=True)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of related entity', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the transaction')),
                ('tenant', models.ForeignKey(help_text='Tenant this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant')),
                ('wallet', models.ForeignKey(help_text='Wallet this transaction affects', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenantwallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('previous_balance', models.DecimalField(decimal_places=2, help_text='Balance before transaction', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of change (positive for credit, negative for debit)', max_digits=12)),
                ('new_balance', models.DecimalField(decimal_places=2, help_text='Balance after transaction', max_digits=12)),
                ('transaction', models.ForeignKey(help_text='Transaction that caused this balance change', on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='tenants.transaction')),
                ('wallet', models.ForeignKey(help_text='Wallet this audit record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='tenants.tenantwallet')),
            ],
            options={
                'db_table': 'wallet_audits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='wallet_audi_wallet__b9963d_idx'), models.Index(fields=['transaction'], name='wallet_audi_transac_1375b2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'transaction_type', 'created_at'], name='transaction_tenant__f1f6a7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'status'], name='transaction_wallet__127b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status', 'created_at'], name='transaction_transac_375222_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='transaction_referen_c8c45f_idx'),
        ),
    ]
