# Generated by Django 4.2.11 on 2025-11-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
        ('tenants', '0003_add_wallet_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the transaction (for four-eyes approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to='rbac.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the transaction (for four-eyes approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transactions', to='rbac.user'),
        ),
    ]
