# Generated by Django 4.2.11 on 2025-11-11 08:54

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_four_eyes_approval_to_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('twilio_sid', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted Twilio Account SID', max_length=500, null=True)),
                ('twilio_token', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted Twilio Auth Token', max_length=500, null=True)),
                ('twilio_webhook_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted Twilio webhook signature secret', max_length=500, null=True)),
                ('woo_store_url', models.URLField(blank=True, help_text='WooCommerce store URL', null=True)),
                ('woo_consumer_key', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted WooCommerce consumer key', max_length=500, null=True)),
                ('woo_consumer_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted WooCommerce consumer secret', max_length=500, null=True)),
                ('woo_webhook_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted WooCommerce webhook secret', max_length=500, null=True)),
                ('shopify_shop_domain', models.CharField(blank=True, help_text='Shopify shop domain (e.g., mystore.myshopify.com)', max_length=255, null=True)),
                ('shopify_access_token', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted Shopify Admin API access token', max_length=500, null=True)),
                ('shopify_webhook_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted Shopify webhook secret', max_length=500, null=True)),
                ('whatsapp_business_id', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted WhatsApp Business Account ID', max_length=500, null=True)),
                ('whatsapp_access_token', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted WhatsApp Business API access token', max_length=500, null=True)),
                ('openai_api_key', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted OpenAI API key', max_length=500, null=True)),
                ('openai_org_id', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted OpenAI organization ID', max_length=500, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID for this tenant', max_length=255, null=True)),
                ('stripe_payment_methods', models.JSONField(blank=True, default=list, help_text='List of Stripe PaymentMethod IDs: [{id, last4, brand, exp_month, exp_year, is_default}]')),
                ('payout_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('paypal', 'PayPal')], help_text='Payout method for tenant earnings', max_length=50, null=True)),
                ('payout_details', apps.core.fields.EncryptedTextField(blank=True, help_text='Encrypted JSON with payout account details', null=True)),
                ('notification_settings', models.JSONField(blank=True, default=dict, help_text='Notification preferences by channel and event type')),
                ('feature_flags', models.JSONField(blank=True, default=dict, help_text='Feature flags for gradual rollout and A/B testing')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Business hours by day of week')),
                ('integrations_status', models.JSONField(blank=True, default=dict, help_text='Status and metadata for each integration')),
                ('branding', models.JSONField(blank=True, default=dict, help_text='Branding and customization settings')),
                ('compliance_settings', models.JSONField(blank=True, default=dict, help_text='GDPR, data retention, and legal compliance settings')),
                ('tenant', models.OneToOneField(help_text='Associated tenant', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
                'db_table': 'tenant_settings',
            },
        ),
    ]
