# Generated by Django 4.2.11 on 2025-11-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_tenant_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether all required onboarding steps are complete'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='When onboarding was completed', null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='onboarding_status',
            field=models.JSONField(blank=True, default=dict, help_text='Onboarding step completion status with timestamps'),
        ),
    ]
