# Generated by Django 4.2.11 on 2025-11-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_onboarding_tracking'),
        ('tenants', '0006_customer_payment_preferences'),
    ]

    operations = [
    ]
