# Generated by Django 4.2.11 on 2025-11-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_merge_20251113_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_preferences',
        ),
    ]
