# Generated by Django 4.2.11 on 2025-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_remove_customer_payment_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Customer payment preferences: {preferred_provider, saved_methods: [{provider, details}]}'),
        ),
    ]
