# Generated by Django 4.2.11 on 2025-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_customer_payment_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional settings metadata (payment provider credentials, etc.)'),
        ),
    ]
