# Generated by Django 4.2.11 on 2025-11-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenantsettings_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='llm_provider',
            field=models.CharField(
                max_length=50,
                default='openai',
                help_text='LLM provider to use (openai, together, etc.)'
            ),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='llm_timeout',
            field=models.FloatField(
                null=True,
                blank=True,
                help_text='Timeout in seconds for LLM API calls'
            ),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='llm_max_retries',
            field=models.IntegerField(
                null=True,
                blank=True,
                help_text='Maximum number of retries for LLM API calls'
            ),
        ),
    ]
