# Generated by Django 4.2.11 on 2025-11-15 04:09

from django.db import migrations
from apps.core.fields import EncryptedCharField


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_llm_configuration_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='together_api_key',
            field=EncryptedCharField(
                max_length=500,
                null=True,
                blank=True,
                help_text="Encrypted Together AI API key"
            ),
        ),
    ]
