# Generated by Django 4.2.11 on 2025-11-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_settings_feature_flags'),
        ('tenants', '0012_add_together_ai_configuration'),
    ]

    operations = [
    ]
