# Generated by Django 4.2.11 on 2025-12-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_add_gemini_api_key'),
        ('tenants', '0014_merge_20251119_1633'),
    ]

    operations = [
    ]
