# Generated by Django 4.2.11 on 2025-12-20 05:58

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_merge_20251220_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_flags',
            field=models.JSONField(blank=True, default=dict, help_text="Detailed consent flags: {'marketing': True/False, 'notifications': True/False, 'data_processing': True/False}"),
        ),
        migrations.AddField(
            model_name='customer',
            name='language_preference',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('sw', 'Swahili'), ('sheng', 'Sheng'), ('mixed', 'Mixed')], help_text="Customer's preferred language for conversations", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_opt_in',
            field=models.BooleanField(blank=True, help_text='Customer consent for marketing communications (null=not set, True=opted in, False=opted out)', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='allowed_languages',
            field=models.JSONField(blank=True, default=apps.tenants.models.default_allowed_languages, help_text="Languages allowed for this tenant (e.g., ['en', 'sw', 'sheng'])"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bot_name',
            field=models.CharField(default='Assistant', help_text='Custom bot name for conversations', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('sheng', 'Sheng')], default='en', help_text='Default language for conversations', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='escalation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Human escalation rules and triggers configuration'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_chattiness_level',
            field=models.IntegerField(choices=[(0, 'Strictly Business'), (1, 'Minimal Friendliness'), (2, 'Friendly but Bounded'), (3, 'More Friendly')], default=2, help_text='Maximum chattiness level for cost control (0-3)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='payment_methods_enabled',
            field=models.JSONField(blank=True, default=dict, help_text="Enabled payment methods: {'mpesa_stk': True, 'mpesa_c2b': True, 'pesapal_card': False}"),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tone_style',
            field=models.CharField(choices=[('friendly_concise', 'Friendly & Concise'), ('professional', 'Professional'), ('casual', 'Casual'), ('formal', 'Formal')], default='friendly_concise', help_text='Communication tone and style', max_length=50),
        ),
    ]
