# Generated by Django 4.2.11 on 2025-11-10 11:09

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_add_wallet_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('action', models.CharField(db_index=True, help_text="Action performed (e.g., 'role_assigned', 'permission_denied', 'product_created')", max_length=100)),
                ('target_type', models.CharField(db_index=True, help_text="Type of target entity (e.g., 'Role', 'Product', 'Withdrawal')", max_length=50)),
                ('target_id', models.UUIDField(blank=True, db_index=True, help_text='ID of target entity', null=True)),
                ('diff', models.JSONField(blank=True, default=dict, help_text='Before/after changes in JSON format')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('request_id', models.UUIDField(blank=True, db_index=True, help_text='Request ID for tracing', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context metadata')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('code', models.CharField(db_index=True, help_text="Unique permission code (e.g., 'catalog:view')", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g., 'View Catalog')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission grants')),
                ('category', models.CharField(db_index=True, help_text="Permission category (e.g., 'catalog', 'finance', 'users')", max_length=50)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Role name (e.g., 'Owner', 'Catalog Manager')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('is_system', models.BooleanField(db_index=True, default=False, help_text='Whether this is a system-seeded role')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['role', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether membership is active')),
                ('invite_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], db_index=True, default='pending', help_text='Invitation status', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True, help_text='When invitation was sent')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When user accepted invitation', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Last activity timestamp in this tenant', null=True)),
            ],
            options={
                'db_table': 'tenant_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantUserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When role was assigned')),
            ],
            options={
                'db_table': 'tenant_user_roles',
                'ordering': ['tenant_user', 'role'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('email', models.EmailField(db_index=True, help_text='User email address (unique globally)', max_length=254, unique=True)),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted phone number', max_length=500, null=True)),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether user account is active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Platform administrator (use sparingly in production)')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled')),
                ('two_factor_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted 2FA secret', max_length=500, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('first_name', models.CharField(blank=True, help_text='User first name', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='User last name', max_length=100)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('granted', models.BooleanField(help_text='True = grant, False = deny (deny wins over role grants)')),
                ('reason', models.TextField(blank=True, help_text='Reason for this override')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who created this override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides_made', to='rbac.user')),
                ('permission', models.ForeignKey(help_text='Permission being granted or denied', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='rbac.permission')),
                ('tenant_user', models.ForeignKey(help_text='Tenant user this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='rbac.tenantuser')),
            ],
            options={
                'db_table': 'user_permissions',
                'ordering': ['tenant_user', 'permission'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'created_at'], name='users_is_acti_e3fac2_idx'),
        ),
        migrations.AddField(
            model_name='tenantuserrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to='rbac.user'),
        ),
        migrations.AddField(
            model_name='tenantuserrole',
            name='role',
            field=models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='tenantuserrole',
            name='tenant_user',
            field=models.ForeignKey(help_text='Tenant user who has this role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.tenantuser'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='User who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='rbac.user'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to='rbac.user'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(help_text='Permission being granted', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(help_text='Role that grants this permission', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='permissions_code_a0a529_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['category'], name='permissions_categor_b3ddb9_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this action belongs to (null for platform-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='rbac.user'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['tenant_user', 'granted'], name='user_permis_tenant__0fb21e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission'], name='user_permis_permiss_1d7e7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('tenant_user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='tenantuserrole',
            index=models.Index(fields=['tenant_user'], name='tenant_user_tenant__572b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuserrole',
            index=models.Index(fields=['role'], name='tenant_user_role_id_59ce79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuserrole',
            unique_together={('tenant_user', 'role')},
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'user', 'is_active'], name='tenant_user_tenant__6434ff_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['user', 'is_active'], name='tenant_user_user_id_088718_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['invite_status', 'is_active'], name='tenant_user_invite__6b7154_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'last_seen_at'], name='tenant_user_tenant__9c6a3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='role_permis_role_id_0ea48f_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='role_permis_permiss_96a6c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_system'], name='roles_tenant__b7923f_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'name'], name='roles_tenant__74cc42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='audit_logs_tenant__0b1a88_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'action', 'created_at'], name='audit_logs_tenant__b6d72a_idx'),
        ),
    ]
