# Generated by Django 4.2.16 on 2025-12-30 09:30

import apps.core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('email', models.EmailField(db_index=True, help_text='User email address (unique globally)', max_length=254, unique=True)),
                ('phone', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted phone number', max_length=500, null=True)),
                ('password_hash', models.CharField(db_column='password_hash', help_text='Hashed password', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether user account is active')),
                ('is_superuser', models.BooleanField(default=False, help_text='Platform administrator (use sparingly in production)')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether 2FA is enabled')),
                ('two_factor_secret', apps.core.fields.EncryptedCharField(blank=True, help_text='Encrypted 2FA secret', max_length=500, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('email_verified', models.BooleanField(db_index=True, default=False, help_text='Whether email has been verified')),
                ('email_verification_token', models.CharField(blank=True, db_index=True, help_text='Email verification token', max_length=255, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, help_text='When verification email was sent', null=True)),
                ('first_name', models.CharField(blank=True, help_text='User first name', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='User last name', max_length=100)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('action', models.CharField(db_index=True, help_text="Action performed (e.g., 'role_assigned', 'permission_denied', 'product_created')", max_length=100)),
                ('target_type', models.CharField(db_index=True, help_text="Type of target entity (e.g., 'Role', 'Product', 'Withdrawal')", max_length=50)),
                ('target_id', models.UUIDField(blank=True, db_index=True, help_text='ID of target entity', null=True)),
                ('diff', models.JSONField(blank=True, default=dict, help_text='Before/after changes in JSON format')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('request_id', models.UUIDField(blank=True, db_index=True, help_text='Request ID for tracing', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context metadata')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('token', models.CharField(db_index=True, help_text='Unique reset token', max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Token expiration time (24 hours from creation)')),
                ('used', models.BooleanField(db_index=True, default=False, help_text='Whether token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When token was used', null=True)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('code', models.CharField(db_index=True, help_text="Unique permission code (e.g., 'catalog:view')", max_length=100, unique=True)),
                ('label', models.CharField(help_text="Human-readable label (e.g., 'View Catalog')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission grants')),
                ('category', models.CharField(db_index=True, help_text="Permission category (e.g., 'catalog', 'finance', 'users')", max_length=50)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('name', models.CharField(help_text="Role name (e.g., 'Owner', 'Catalog Manager')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('is_system', models.BooleanField(db_index=True, default=False, help_text='Whether this is a system-seeded role')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['role', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether membership is active')),
                ('invite_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], db_index=True, default='pending', help_text='Invitation status', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True, help_text='When invitation was sent')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When user accepted invitation', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, help_text='Last activity timestamp in this tenant', null=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='User who sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('granted', models.BooleanField(help_text='True = grant, False = deny (deny wins over role grants)')),
                ('reason', models.TextField(blank=True, help_text='Reason for this override')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who created this override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides_made', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(help_text='Permission being granted or denied', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='rbac.permission')),
                ('tenant_user', models.ForeignKey(help_text='Tenant user this override applies to', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='rbac.tenantuser')),
            ],
            options={
                'db_table': 'user_permissions',
                'ordering': ['tenant_user', 'permission'],
            },
        ),
        migrations.CreateModel(
            name='TenantUserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When role was assigned')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role assigned to the user', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role')),
                ('tenant_user', models.ForeignKey(help_text='Tenant user who has this role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.tenantuser')),
            ],
            options={
                'db_table': 'tenant_user_roles',
                'ordering': ['tenant_user', 'role'],
            },
        ),
    ]
