# Generated by Django 4.2.16 on 2025-12-30 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='user',
            field=models.ForeignKey(help_text='User who is a member', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(help_text='Permission being granted', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(help_text='Role that grants this permission', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['code'], name='permissions_code_a0a529_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['category'], name='permissions_categor_b3ddb9_idx'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(help_text='User this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this action belongs to (null for platform-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'created_at'], name='users_is_acti_e3fac2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified', 'is_active'], name='users_email_v_7fe3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verification_token'], name='users_email_v_9c78de_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['tenant_user', 'granted'], name='user_permis_tenant__0fb21e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission'], name='user_permis_permiss_1d7e7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('tenant_user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='tenantuserrole',
            index=models.Index(fields=['tenant_user'], name='tenant_user_tenant__572b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuserrole',
            index=models.Index(fields=['role'], name='tenant_user_role_id_59ce79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuserrole',
            unique_together={('tenant_user', 'role')},
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'user', 'is_active'], name='tenant_user_tenant__6434ff_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['user', 'is_active'], name='tenant_user_user_id_088718_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['invite_status', 'is_active'], name='tenant_user_invite__6b7154_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'last_seen_at'], name='tenant_user_tenant__9c6a3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role'], name='role_permis_role_id_0ea48f_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='role_permis_permiss_96a6c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_system'], name='roles_tenant__b7923f_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'name'], name='roles_tenant__74cc42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token', 'expires_at', 'used'], name='password_re_token_d8053e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'expires_at'], name='password_re_user_id_13cacb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'created_at'], name='audit_logs_tenant__0b1a88_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant', 'action', 'created_at'], name='audit_logs_tenant__b6d72a_idx'),
        ),
    ]
