# Generated by Django 4.2.11 on 2025-11-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_add_email_verification_and_password_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(db_column='password_hash', help_text='Hashed password', max_length=255),
        ),
    ]
