# Generated by Django 4.2.16 on 2025-12-30 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('date', models.DateField(db_index=True, help_text='Date for these metrics')),
                ('msgs_in', models.IntegerField(default=0, help_text='Number of inbound messages')),
                ('msgs_out', models.IntegerField(default=0, help_text='Number of outbound messages')),
                ('conversations', models.IntegerField(default=0, help_text='Number of new conversations started')),
                ('avg_first_response_secs', models.FloatField(blank=True, help_text='Average first response time in seconds', null=True)),
                ('handoffs', models.IntegerField(default=0, help_text='Number of conversations handed off to humans')),
                ('enquiries', models.IntegerField(default=0, help_text='Number of product/service enquiries')),
                ('orders', models.IntegerField(default=0, help_text='Number of orders created')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from paid/fulfilled orders', max_digits=12)),
                ('bookings', models.IntegerField(default=0, help_text='Number of appointments booked')),
                ('booking_conversion_rate', models.FloatField(blank=True, help_text='Bookings divided by availability checks', null=True)),
                ('no_show_rate', models.FloatField(blank=True, help_text='No-shows divided by confirmed appointments', null=True)),
                ('campaign_sends', models.IntegerField(default=0, help_text='Number of campaign messages sent')),
                ('campaign_responses', models.IntegerField(default=0, help_text='Number of responses to campaign messages')),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'db_table': 'analytics_daily',
                'ordering': ['-date'],
            },
        ),
    ]
