# Generated by Django 4.2.16 on 2025-12-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsdaily',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='analyticsdaily',
            index=models.Index(fields=['tenant', 'date'], name='analytics_d_tenant__0a2cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdaily',
            index=models.Index(fields=['tenant', '-date'], name='analytics_d_tenant__5707de_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdaily',
            index=models.Index(fields=['date'], name='analytics_d_date_9d1a51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsdaily',
            unique_together={('tenant', 'date')},
        ),
    ]
