# Generated by Django 4.2.11 on 2025-11-10 09:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_add_wallet_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('external_source', models.CharField(blank=True, choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('manual', 'Manual')], help_text='Source system for synchronized products', max_length=20, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Product ID in external system', max_length=255, null=True)),
                ('title', models.CharField(db_index=True, help_text='Product title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, help_text='Available stock quantity (null = unlimited)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether product is active and visible')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional product metadata')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Full-text search vector', null=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this product belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('title', models.CharField(help_text="Variant title (e.g., 'Large / Red')", max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit for this variant', max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, help_text='Available stock quantity (null = unlimited)', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Variant-specific price (null = use product price)', max_digits=10, null=True)),
                ('attrs', models.JSONField(blank=True, default=dict, help_text="Variant attributes (e.g., {'size': 'L', 'color': 'red'})")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional variant metadata')),
                ('product', models.ForeignKey(help_text='Product this variant belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='product_var_product_3bfeed_idx'), models.Index(fields=['sku'], name='product_var_sku_3a95f0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'is_active'], name='products_tenant__76cb13_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'title'], name='products_tenant__714ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'external_source', 'external_id'], name='products_tenant__a79e75_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'created_at'], name='products_tenant__3eefd6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='product_search_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'external_source', 'external_id')},
        ),
    ]
