# Generated by Django 4.2.11 on 2025-11-10 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('intent_name', models.CharField(db_index=True, help_text='Classified intent name (e.g., BROWSE_PRODUCTS, BOOK_APPOINTMENT)', max_length=100)),
                ('confidence_score', models.FloatField(help_text='Confidence score from 0.0 to 1.0')),
                ('slots', models.JSONField(blank=True, default=dict, help_text='Extracted entities/slots from the message')),
                ('model', models.CharField(help_text='AI model used for classification (e.g., gpt-4, claude-3)', max_length=50)),
                ('message_text', models.TextField(help_text='Original message text that was classified')),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken to classify intent in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (prompt tokens, response tokens, etc.)')),
                ('conversation', models.ForeignKey(help_text='Conversation this intent belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='intent_events', to='messaging.conversation')),
            ],
            options={
                'db_table': 'intent_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='intent_even_convers_716fb2_idx'), models.Index(fields=['intent_name', 'created_at'], name='intent_even_intent__fe7c6c_idx'), models.Index(fields=['confidence_score'], name='intent_even_confide_e94137_idx'), models.Index(fields=['conversation', 'intent_name'], name='intent_even_convers_038bef_idx')],
            },
        ),
    ]
