# Generated by Django 4.2.7 on 2025-12-22 12:58

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        default="Assistant",
                        help_text="Name of the AI agent (e.g., 'Sarah', 'TechBot')",
                        max_length=100,
                    ),
                ),
                (
                    "personality_traits",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Personality traits as key-value pairs (e.g., {'helpful': true, 'empathetic': true})",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("casual", "Casual"),
                            ("formal", "Formal"),
                        ],
                        default="friendly",
                        help_text="Communication tone for the agent",
                        max_length=20,
                    ),
                ),
                (
                    "default_model",
                    models.CharField(
                        default="gpt-4o",
                        help_text="Default LLM model to use (e.g., 'gpt-4o', 'o1-preview', 'o1-mini')",
                        max_length=50,
                    ),
                ),
                (
                    "fallback_models",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of fallback models to try if default fails (e.g., ['gpt-4o-mini', 'gpt-3.5-turbo'])",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Temperature for response generation (0.0-2.0, higher = more creative)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "max_response_length",
                    models.IntegerField(
                        default=500,
                        help_text="Maximum length of agent responses in characters",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "behavioral_restrictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of topics or behaviors to avoid (e.g., ['politics', 'medical advice'])",
                    ),
                ),
                (
                    "required_disclaimers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of disclaimers to include in responses (e.g., ['I am an AI assistant'])",
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Minimum confidence score to proceed without handoff (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "auto_handoff_topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Topics that always trigger handoff to human (e.g., ['refund', 'complaint'])",
                    ),
                ),
                (
                    "max_low_confidence_attempts",
                    models.IntegerField(
                        default=2,
                        help_text="Number of low-confidence responses before triggering handoff",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "enable_proactive_suggestions",
                    models.BooleanField(
                        default=True,
                        help_text="Enable proactive product/service suggestions",
                    ),
                ),
                (
                    "enable_spelling_correction",
                    models.BooleanField(
                        default=True,
                        help_text="Enable automatic spelling correction for customer messages",
                    ),
                ),
                (
                    "enable_rich_messages",
                    models.BooleanField(
                        default=True,
                        help_text="Enable rich WhatsApp messages (buttons, lists, media)",
                    ),
                ),
                (
                    "enable_feedback_collection",
                    models.BooleanField(
                        default=True,
                        help_text="Enable feedback collection buttons after bot responses",
                    ),
                ),
                (
                    "feedback_frequency",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("sometimes", "Sometimes (every 3rd message)"),
                            ("never", "Never"),
                        ],
                        default="sometimes",
                        help_text="How often to show feedback buttons",
                        max_length=20,
                    ),
                ),
                (
                    "enable_grounded_validation",
                    models.BooleanField(
                        default=True,
                        help_text="Enable validation that responses are grounded in actual data (prevents hallucinations)",
                    ),
                ),
                (
                    "enable_document_retrieval",
                    models.BooleanField(
                        default=False,
                        help_text="Enable retrieval from uploaded documents",
                    ),
                ),
                (
                    "enable_database_retrieval",
                    models.BooleanField(
                        default=True,
                        help_text="Enable retrieval from database (products, services, orders)",
                    ),
                ),
                (
                    "enable_internet_enrichment",
                    models.BooleanField(
                        default=False,
                        help_text="Enable internet search for product enrichment",
                    ),
                ),
                (
                    "enable_source_attribution",
                    models.BooleanField(
                        default=True, help_text="Include source citations in responses"
                    ),
                ),
                (
                    "max_document_results",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum number of document chunks to retrieve",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "max_database_results",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of database results to retrieve",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "max_internet_results",
                    models.IntegerField(
                        default=2,
                        help_text="Maximum number of internet search results",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "semantic_search_weight",
                    models.FloatField(
                        default=0.7,
                        help_text="Weight for semantic search in hybrid search (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "keyword_search_weight",
                    models.FloatField(
                        default=0.3,
                        help_text="Weight for keyword search in hybrid search (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-small",
                        help_text="Embedding model for semantic search",
                        max_length=50,
                    ),
                ),
                (
                    "agent_can_do",
                    models.TextField(
                        blank=True,
                        help_text="Explicit list of what the agent CAN do (for prompt engineering)",
                    ),
                ),
                (
                    "agent_cannot_do",
                    models.TextField(
                        blank=True,
                        help_text="Explicit list of what the agent CANNOT do (for prompt engineering)",
                    ),
                ),
                (
                    "use_business_name_as_identity",
                    models.BooleanField(
                        default=True,
                        help_text="Use tenant's business name in bot identity",
                    ),
                ),
                (
                    "custom_bot_greeting",
                    models.TextField(
                        blank=True,
                        help_text="Custom greeting message for first contact (overrides default)",
                    ),
                ),
                (
                    "monthly_llm_budget_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Monthly LLM budget in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "llm_budget_exceeded_action",
                    models.CharField(
                        choices=[
                            ("fallback", "Fallback to rules"),
                            ("throttle", "Throttle usage"),
                            ("stop", "Stop LLM usage"),
                        ],
                        default="fallback",
                        help_text="Action to take when LLM budget is exceeded",
                        max_length=20,
                    ),
                ),
                (
                    "business_hours_start",
                    models.TimeField(
                        default="08:00:00", help_text="Business hours start time"
                    ),
                ),
                (
                    "business_hours_end",
                    models.TimeField(
                        default="20:00:00", help_text="Business hours end time"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Quiet hours start time (no automated messages)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, help_text="Quiet hours end time", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Configuration",
                "verbose_name_plural": "Agent Configurations",
                "db_table": "agent_configurations",
            },
        ),
        migrations.CreateModel(
            name="AgentInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "customer_message",
                    models.TextField(help_text="Original customer message text"),
                ),
                (
                    "detected_intents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of detected intents with confidence scores",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        db_index=True,
                        help_text="LLM model used for this interaction (e.g., 'gpt-4o', 'o1-preview')",
                        max_length=50,
                    ),
                ),
                (
                    "context_size",
                    models.IntegerField(
                        default=0,
                        help_text="Size of context provided to the model in tokens",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Time taken to process and generate response in milliseconds",
                    ),
                ),
                (
                    "agent_response",
                    models.TextField(help_text="Generated agent response text"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        db_index=True,
                        help_text="Confidence score for the response (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "handoff_triggered",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this interaction triggered a handoff to human agent",
                    ),
                ),
                (
                    "handoff_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for handoff (e.g., 'low_confidence', 'explicit_request', 'restricted_topic')",
                        max_length=100,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("button", "Button"),
                            ("list", "List"),
                            ("media", "Media"),
                        ],
                        db_index=True,
                        default="text",
                        help_text="Type of message sent to customer",
                        max_length=20,
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Token usage breakdown (e.g., {'prompt_tokens': 100, 'completion_tokens': 50, 'total_tokens': 150})",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost in USD for this interaction",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Interaction",
                "verbose_name_plural": "Agent Interactions",
                "db_table": "agent_interactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrowseSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "catalog_type",
                    models.CharField(
                        choices=[("products", "Products"), ("services", "Services")],
                        help_text="Type of catalog being browsed",
                        max_length=20,
                    ),
                ),
                (
                    "current_page",
                    models.IntegerField(
                        default=1, help_text="Current page number (1-indexed)"
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(
                        default=5, help_text="Number of items per page"
                    ),
                ),
                (
                    "total_items",
                    models.IntegerField(
                        help_text="Total number of items in result set"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Applied filters (category, price range, etc.)",
                    ),
                ),
                (
                    "search_query",
                    models.TextField(
                        blank=True, help_text="Search query if applicable"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether session is still active",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When session expires (10 minutes from last activity)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Browse Session",
                "verbose_name_plural": "Browse Sessions",
                "db_table": "bot_browse_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "current_topic",
                    models.CharField(
                        blank=True,
                        help_text="Current topic being discussed (e.g., 'product_inquiry', 'booking_appointment')",
                        max_length=100,
                    ),
                ),
                (
                    "pending_action",
                    models.CharField(
                        blank=True,
                        help_text="Pending action waiting for customer input (e.g., 'awaiting_date_selection')",
                        max_length=100,
                    ),
                ),
                (
                    "extracted_entities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extracted entities from conversation (e.g., {'product_name': 'Blue Shirt', 'size': 'L'})",
                    ),
                ),
                (
                    "conversation_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of conversation history for context window management",
                    ),
                ),
                (
                    "key_facts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of key facts to remember (e.g., ['Customer prefers blue', 'Budget is $50'])",
                    ),
                ),
                (
                    "last_interaction",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of last interaction (auto-updated)",
                    ),
                ),
                (
                    "context_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this context expires (null = never expires)",
                        null=True,
                    ),
                ),
                (
                    "clarification_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Number of clarification attempts made before handoff",
                    ),
                ),
                (
                    "shopping_cart",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Shopping cart for multi-item purchases",
                    ),
                ),
                (
                    "language_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether language preference is locked for this conversation",
                    ),
                ),
                (
                    "current_flow",
                    models.CharField(
                        blank=True,
                        help_text="Current flow state (e.g., 'browsing_products', 'checkout', 'booking')",
                        max_length=50,
                    ),
                ),
                (
                    "awaiting_response",
                    models.BooleanField(
                        default=False,
                        help_text="Whether bot is awaiting a specific response from customer",
                    ),
                ),
                (
                    "last_question",
                    models.TextField(
                        blank=True, help_text="Last question asked by bot (for context)"
                    ),
                ),
                (
                    "last_menu",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Last displayed menu for reference resolution (e.g., {'type': 'products', 'items': [...]})",
                    ),
                ),
                (
                    "last_menu_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last_menu was created (for expiration checking)",
                        null=True,
                    ),
                ),
                (
                    "detected_language",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Detected languages (e.g., ['en'], ['sw'], ['sheng'])",
                    ),
                ),
                (
                    "checkout_state",
                    models.CharField(
                        default="browsing",
                        help_text="Current checkout state (browsing, product_selected, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "selected_product_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of currently selected product in checkout",
                        null=True,
                    ),
                ),
                (
                    "selected_quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="Selected quantity for checkout",
                        null=True,
                    ),
                ),
                (
                    "current_session_start",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Start time of current conversation session",
                        null=True,
                    ),
                ),
                (
                    "session_message_count",
                    models.IntegerField(
                        default=0, help_text="Number of messages in current session"
                    ),
                ),
                (
                    "last_bot_message",
                    models.TextField(
                        blank=True,
                        help_text="Last message sent by bot (for echo prevention)",
                    ),
                ),
                (
                    "last_customer_message",
                    models.TextField(
                        blank=True,
                        help_text="Last message sent by customer (for echo prevention)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Context",
                "verbose_name_plural": "Conversation Contexts",
                "db_table": "conversation_contexts",
            },
        ),
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "state_data",
                    models.JSONField(help_text="Serialized ConversationState as JSON"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this session is currently active",
                    ),
                ),
                (
                    "last_request_id",
                    models.CharField(
                        help_text="ID of the last processed request", max_length=255
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional session metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Session",
                "verbose_name_plural": "Conversation Sessions",
                "db_table": "conversation_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("txt", "Text"),
                            ("docx", "Word Document"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processing_progress",
                    models.IntegerField(
                        default=0, help_text="Processing progress percentage (0-100)"
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("chunk_count", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing was completed", null=True
                    ),
                ),
            ],
            options={
                "db_table": "bot_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("content", models.TextField()),
                ("token_count", models.IntegerField(default=0)),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Page number in source document (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Section or heading title (if applicable)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("embedding", models.JSONField(blank=True, null=True)),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-small",
                        help_text="Embedding model used for this chunk",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "db_table": "bot_document_chunks",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="HumanCorrection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "bot_response",
                    models.TextField(
                        help_text="Original bot response that was incorrect"
                    ),
                ),
                (
                    "human_response",
                    models.TextField(help_text="Corrected response from human agent"),
                ),
                (
                    "correction_reason",
                    models.TextField(
                        help_text="Explanation of why correction was needed"
                    ),
                ),
                (
                    "correction_category",
                    models.CharField(
                        choices=[
                            ("factual_error", "Factual Error"),
                            ("tone_inappropriate", "Inappropriate Tone"),
                            ("missing_information", "Missing Information"),
                            ("wrong_intent", "Wrong Intent Detection"),
                            ("poor_recommendation", "Poor Recommendation"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Category of correction",
                        max_length=50,
                    ),
                ),
                (
                    "approved_for_training",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this correction is approved for training data",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this correction was approved",
                        null=True,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Quality rating of the correction (0-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional correction metadata",
                    ),
                ),
            ],
            options={
                "db_table": "bot_human_correction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntentClassificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        help_text="Original message text that was classified"
                    ),
                ),
                (
                    "intent_name",
                    models.CharField(
                        db_index=True,
                        help_text="Classified intent name",
                        max_length=100,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Confidence score for the classification (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        db_index=True,
                        help_text="LLM model used for classification",
                        max_length=50,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Time taken for classification in milliseconds",
                    ),
                ),
                (
                    "all_intents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="All detected intents with scores",
                    ),
                ),
                (
                    "slots",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extracted slots from the message",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (context, features, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intent Classification Log",
                "verbose_name_plural": "Intent Classification Logs",
                "db_table": "bot_intent_classification_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "intent_name",
                    models.CharField(
                        db_index=True,
                        help_text="Classified intent name (e.g., BROWSE_PRODUCTS, BOOK_APPOINTMENT)",
                        max_length=100,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Confidence score from 0.0 to 1.0"),
                ),
                (
                    "slots",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extracted entities/slots from the message",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="AI model used for classification (e.g., gpt-4, claude-3)",
                        max_length=50,
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        help_text="Original message text that was classified"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken to classify intent in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (prompt tokens, response tokens, etc.)",
                    ),
                ),
            ],
            options={
                "db_table": "intent_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractionFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                        ],
                        db_index=True,
                        help_text="User rating (helpful/not_helpful)",
                        max_length=20,
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        blank=True, help_text="Optional text feedback from user"
                    ),
                ),
                (
                    "user_continued",
                    models.BooleanField(
                        default=False,
                        help_text="User continued conversation after bot response",
                    ),
                ),
                (
                    "completed_action",
                    models.BooleanField(
                        default=False,
                        help_text="User completed intended action (purchase, booking, etc.)",
                    ),
                ),
                (
                    "requested_human",
                    models.BooleanField(
                        default=False, help_text="User requested human handoff"
                    ),
                ),
                (
                    "response_time_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken for user to respond (engagement metric)",
                        null=True,
                    ),
                ),
                (
                    "feedback_source",
                    models.CharField(
                        default="whatsapp_button",
                        help_text="Source of feedback (whatsapp_button, api, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional feedback metadata",
                    ),
                ),
            ],
            options={
                "db_table": "bot_interaction_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("faq", "FAQ"),
                            ("policy", "Policy"),
                            ("product_info", "Product Information"),
                            ("service_info", "Service Information"),
                            ("procedure", "Procedure"),
                            ("general", "General Knowledge"),
                        ],
                        db_index=True,
                        default="general",
                        help_text="Type of knowledge entry",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Category for organizing entries (e.g., 'shipping', 'returns', 'technical')",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or question for this entry", max_length=255
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Full content or answer for this entry"),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords for search optimization",
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Vector embedding for semantic search (generated from title + content)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (source, author, related_entries, etc.)",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Priority for ranking search results (0-100, higher = more important)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this entry is active and should be used by the agent",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number for tracking updates"
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Entry",
                "verbose_name_plural": "Knowledge Entries",
                "db_table": "knowledge_entries",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LanguagePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "primary_language",
                    models.CharField(
                        default="en",
                        help_text="Primary language code (en, sw, mixed)",
                        max_length=10,
                    ),
                ),
                (
                    "language_usage",
                    models.JSONField(
                        default=dict, help_text="Usage statistics per language"
                    ),
                ),
                (
                    "common_phrases",
                    models.JSONField(
                        default=list, help_text="Commonly used phrases by this customer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Preference",
                "verbose_name_plural": "Language Preferences",
                "db_table": "bot_language_preferences",
            },
        ),
        migrations.CreateModel(
            name="LLMUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="LLM provider (e.g., 'openai', 'anthropic')",
                        max_length=50,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        db_index=True,
                        help_text="Model name (e.g., 'gpt-4o', 'claude-3-sonnet')",
                        max_length=50,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of task (e.g., 'intent_classification', 'response_generation')",
                        max_length=50,
                    ),
                ),
                (
                    "input_tokens",
                    models.IntegerField(
                        default=0, help_text="Number of input tokens used"
                    ),
                ),
                (
                    "output_tokens",
                    models.IntegerField(
                        default=0, help_text="Number of output tokens generated"
                    ),
                ),
                (
                    "total_tokens",
                    models.IntegerField(
                        default=0, help_text="Total tokens (input + output)"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Cost in USD for this API call",
                        max_digits=10,
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0, help_text="Response time in milliseconds"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the API call was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if the call failed"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (temperature, max_tokens, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Usage Log",
                "verbose_name_plural": "LLM Usage Logs",
                "db_table": "bot_llm_usage_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageHarmonizationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "message_ids",
                    models.JSONField(
                        help_text="List of message IDs that were combined"
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0, help_text="Number of messages combined"
                    ),
                ),
                (
                    "combined_text",
                    models.TextField(help_text="Combined text from all messages"),
                ),
                (
                    "wait_time_ms",
                    models.IntegerField(
                        help_text="Time waited before processing in milliseconds"
                    ),
                ),
                (
                    "first_message_at",
                    models.DateTimeField(
                        help_text="Timestamp of first message in burst"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        help_text="Timestamp of last message in burst"
                    ),
                ),
                (
                    "response_generated",
                    models.TextField(
                        help_text="Generated response to harmonized messages"
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Time taken to generate response in milliseconds",
                    ),
                ),
                (
                    "typing_indicator_shown",
                    models.BooleanField(
                        default=False,
                        help_text="Whether typing indicator was shown during wait",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether harmonization was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if harmonization failed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Harmonization Log",
                "verbose_name_plural": "Message Harmonization Logs",
                "db_table": "bot_message_harmonization_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Payment amount", max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the payment request",
                        max_length=20,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        help_text="Payment provider used (e.g., 'stripe', 'paypal')",
                        max_length=50,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID from payment provider",
                        max_length=255,
                    ),
                ),
                (
                    "initiated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the payment request was initiated",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the payment was completed",
                        null=True,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Error code if payment failed",
                        max_length=50,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if payment failed"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (payment method, customer info, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Request",
                "verbose_name_plural": "Payment Requests",
                "db_table": "bot_payment_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "key_features",
                    models.JSONField(
                        default=list, help_text="List of key product features"
                    ),
                ),
                (
                    "use_cases",
                    models.JSONField(
                        default=list, help_text="Common use cases for this product"
                    ),
                ),
                (
                    "target_audience",
                    models.JSONField(
                        default=list, help_text="Target customer segments"
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Semantic embedding vector for similarity search",
                        null=True,
                    ),
                ),
                ("summary", models.TextField(help_text="AI-generated product summary")),
                (
                    "ai_categories",
                    models.JSONField(
                        default=list,
                        help_text="AI-inferred categories beyond formal taxonomy",
                    ),
                ),
                (
                    "ai_tags",
                    models.JSONField(
                        default=list,
                        help_text="AI-generated tags for search and matching",
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When analysis was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Analysis",
                "verbose_name_plural": "Product Analyses",
                "db_table": "bot_product_analyses",
            },
        ),
        migrations.CreateModel(
            name="ReferenceContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when the record was soft deleted",
                        null=True,
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        help_text="Unique identifier for this context", max_length=50
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("products", "Products"),
                            ("services", "Services"),
                            ("appointments", "Appointments"),
                            ("orders", "Orders"),
                        ],
                        help_text="Type of items in the list",
                        max_length=20,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        help_text="List of items with IDs and display info"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When context expires (5 minutes from creation)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Context",
                "verbose_name_plural": "Reference Contexts",
                "db_table": "bot_reference_contexts",
                "ordering": ["-created_at"],
            },
        ),
    ]
