# Generated by Django 4.2.11 on 2025-11-10 21:31

from django.db import migrations, models
import django.db.models.deletion


def populate_tenant_from_conversation(apps, schema_editor):
    """Populate tenant field from conversation.tenant for existing records."""
    IntentEvent = apps.get_model('bot', 'IntentEvent')
    for intent_event in IntentEvent.objects.all():
        intent_event.tenant = intent_event.conversation.tenant
        intent_event.save(update_fields=['tenant'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_four_eyes_approval_to_transactions'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='intentevent',
            name='intent_even_intent__fe7c6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='intentevent',
            name='intent_even_confide_e94137_idx',
        ),
        migrations.AddField(
            model_name='intentevent',
            name='tenant',
            field=models.ForeignKey(
                null=True,
                help_text='Tenant this intent event belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='intent_events',
                to='tenants.tenant'
            ),
        ),
        migrations.RunPython(populate_tenant_from_conversation, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='intentevent',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this intent event belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='intent_events',
                to='tenants.tenant'
            ),
        ),
        migrations.AddIndex(
            model_name='intentevent',
            index=models.Index(fields=['tenant', 'created_at'], name='intent_even_tenant__cf56ed_idx'),
        ),
        migrations.AddIndex(
            model_name='intentevent',
            index=models.Index(fields=['tenant', 'intent_name', 'created_at'], name='intent_even_tenant__f3ba44_idx'),
        ),
        migrations.AddIndex(
            model_name='intentevent',
            index=models.Index(fields=['tenant', 'confidence_score'], name='intent_even_tenant__0b34e3_idx'),
        ),
    ]
