# Generated by Django 4.2.7 on 2025-12-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot", "0001_initial"),
        ("catalog", "0001_initial"),
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencecontext",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reference_contexts",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="productanalysis",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_analysis",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this payment was initiated from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_requests",
                to="messaging.conversation",
            ),
        ),
    ]
