# Generated by Django 4.2.7 on 2025-12-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot", "0002_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Order this payment is for (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_requests",
                to="orders.order",
            ),
        ),
    ]
