# Generated by Django 4.2.11 on 2025-11-14 08:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_llm_configuration_fields'),
        ('bot', '0002_add_tenant_to_intent_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('agent_name', models.CharField(default='Assistant', help_text="Name of the AI agent (e.g., 'Sarah', 'TechBot')", max_length=100)),
                ('personality_traits', models.JSONField(blank=True, default=dict, help_text="Personality traits as key-value pairs (e.g., {'helpful': true, 'empathetic': true})")),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('casual', 'Casual'), ('formal', 'Formal')], default='friendly', help_text='Communication tone for the agent', max_length=20)),
                ('default_model', models.CharField(default='gpt-4o', help_text="Default LLM model to use (e.g., 'gpt-4o', 'o1-preview', 'o1-mini')", max_length=50)),
                ('fallback_models', models.JSONField(blank=True, default=list, help_text="List of fallback models to try if default fails (e.g., ['gpt-4o-mini', 'gpt-3.5-turbo'])")),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature for response generation (0.0-2.0, higher = more creative)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_response_length', models.IntegerField(default=500, help_text='Maximum length of agent responses in characters', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(2000)])),
                ('behavioral_restrictions', models.JSONField(blank=True, default=list, help_text="List of topics or behaviors to avoid (e.g., ['politics', 'medical advice'])")),
                ('required_disclaimers', models.JSONField(blank=True, default=list, help_text="List of disclaimers to include in responses (e.g., ['I am an AI assistant'])")),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Minimum confidence score to proceed without handoff (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('auto_handoff_topics', models.JSONField(blank=True, default=list, help_text="Topics that always trigger handoff to human (e.g., ['refund', 'complaint'])")),
                ('max_low_confidence_attempts', models.IntegerField(default=2, help_text='Number of low-confidence responses before triggering handoff', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('enable_proactive_suggestions', models.BooleanField(default=True, help_text='Enable proactive product/service suggestions')),
                ('enable_spelling_correction', models.BooleanField(default=True, help_text='Enable automatic spelling correction for customer messages')),
                ('enable_rich_messages', models.BooleanField(default=True, help_text='Enable rich WhatsApp messages (buttons, lists, media)')),
                ('tenant', models.OneToOneField(help_text='Tenant this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agent_configuration', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
                'db_table': 'agent_configurations',
            },
        ),
    ]
