# Generated by Django 4.2.11 on 2025-11-14 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_add_llm_configuration_fields'),
        ('bot', '0003_add_agent_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('entry_type', models.CharField(choices=[('faq', 'FAQ'), ('policy', 'Policy'), ('product_info', 'Product Information'), ('service_info', 'Service Information'), ('procedure', 'Procedure'), ('general', 'General Knowledge')], db_index=True, default='general', help_text='Type of knowledge entry', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, help_text="Category for organizing entries (e.g., 'shipping', 'returns', 'technical')", max_length=100)),
                ('title', models.CharField(help_text='Title or question for this entry', max_length=255)),
                ('content', models.TextField(help_text='Full content or answer for this entry')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for search optimization')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic search (generated from title + content)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (source, author, related_entries, etc.)')),
                ('priority', models.IntegerField(default=0, help_text='Priority for ranking search results (0-100, higher = more important)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this entry is active and should be used by the agent')),
                ('version', models.IntegerField(default=1, help_text='Version number for tracking updates')),
                ('tenant', models.ForeignKey(help_text='Tenant this knowledge entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries',
                'db_table': 'knowledge_entries',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'priority'], name='knowledge_e_tenant__0060bf_idx'), models.Index(fields=['tenant', 'entry_type', 'is_active'], name='knowledge_e_tenant__dde4be_idx'), models.Index(fields=['tenant', 'category', 'is_active'], name='knowledge_e_tenant__cd1b2b_idx'), models.Index(fields=['tenant', 'created_at'], name='knowledge_e_tenant__090c22_idx')],
            },
        ),
    ]
