# Generated by Django 4.2.7 on 2025-12-22 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("messaging", "0002_initial"),
        ("services", "0001_initial"),
        ("catalog", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bot", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this payment request belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_requests",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="messageharmonizationlog",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this harmonization belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="harmonization_logs",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="Conversation this usage belongs to (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_usage_logs",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="llmusagelog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this usage belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_usage_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="languagepreference",
            name="conversation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="language_preference",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeentry",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this knowledge entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_entries",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="interactionfeedback",
            name="agent_interaction",
            field=models.ForeignKey(
                help_text="Agent interaction being rated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="bot.agentinteraction",
            ),
        ),
        migrations.AddField(
            model_name="interactionfeedback",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this feedback belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interaction_feedback",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="interactionfeedback",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer who provided feedback",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interaction_feedback",
                to="tenants.customer",
            ),
        ),
        migrations.AddField(
            model_name="interactionfeedback",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this feedback belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interaction_feedback",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="intentevent",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this intent belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intent_events",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="intentevent",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this intent event belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intent_events",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="intentclassificationlog",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this classification belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intent_logs",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="intentclassificationlog",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this log belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intent_classification_logs",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="agent_interaction",
            field=models.ForeignKey(
                help_text="Agent interaction that was corrected",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_corrections",
                to="bot.agentinteraction",
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this correction for training",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this correction belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_corrections",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Human agent who made the correction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bot_corrections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="humancorrection",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this correction belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_corrections",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="bot.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="conversation",
            field=models.OneToOneField(
                help_text="Conversation this session belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="customer",
            field=models.ForeignKey(
                help_text="Customer this session belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_sessions",
                to="tenants.customer",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this session belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_sessions",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="conversationcontext",
            name="conversation",
            field=models.OneToOneField(
                help_text="Conversation this context belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="context",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationcontext",
            name="last_product_viewed",
            field=models.ForeignKey(
                blank=True,
                help_text="Last product the customer viewed or inquired about",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="context_views",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="conversationcontext",
            name="last_service_viewed",
            field=models.ForeignKey(
                blank=True,
                help_text="Last service the customer viewed or inquired about",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="context_views",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="browsesession",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this browse session belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="browse_sessions",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="browsesession",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this browse session belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="browse_sessions",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="agentinteraction",
            name="conversation",
            field=models.ForeignKey(
                help_text="Conversation this interaction belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_interactions",
                to="messaging.conversation",
            ),
        ),
        migrations.AddField(
            model_name="agentconfiguration",
            name="tenant",
            field=models.OneToOneField(
                help_text="Tenant this configuration belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_configuration",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="referencecontext",
            index=models.Index(
                fields=["conversation", "expires_at"],
                name="bot_referen_convers_c631ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referencecontext",
            index=models.Index(
                fields=["context_id"], name="bot_referen_context_b126ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productanalysis",
            index=models.Index(
                fields=["product"], name="bot_product_product_8d47a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productanalysis",
            index=models.Index(
                fields=["analyzed_at"], name="bot_product_analyze_c6b1ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["tenant", "created_at"], name="bot_payment_tenant__d0d832_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["tenant", "status"], name="bot_payment_tenant__fb7e05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="bot_payment_convers_5a5cb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["status", "created_at"], name="bot_payment_status_daea4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageharmonizationlog",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="bot_message_convers_677629_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messageharmonizationlog",
            index=models.Index(
                fields=["conversation", "success"],
                name="bot_message_convers_b134a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messageharmonizationlog",
            index=models.Index(
                fields=["created_at"], name="bot_message_created_e23de9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=["tenant", "created_at"], name="bot_llm_usa_tenant__5cf903_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=["tenant", "provider", "created_at"],
                name="bot_llm_usa_tenant__57a6d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=["tenant", "model", "created_at"],
                name="bot_llm_usa_tenant__daccca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="llmusagelog",
            index=models.Index(
                fields=["task_type", "created_at"],
                name="bot_llm_usa_task_ty_05bbe9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="languagepreference",
            index=models.Index(
                fields=["conversation"], name="bot_languag_convers_923042_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["tenant", "is_active", "priority"],
                name="knowledge_e_tenant__0060bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["tenant", "entry_type", "is_active"],
                name="knowledge_e_tenant__dde4be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["tenant", "category", "is_active"],
                name="knowledge_e_tenant__cd1b2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeentry",
            index=models.Index(
                fields=["tenant", "created_at"], name="knowledge_e_tenant__090c22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionfeedback",
            index=models.Index(
                fields=["tenant", "created_at"], name="bot_interac_tenant__48f6fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionfeedback",
            index=models.Index(
                fields=["tenant", "rating", "created_at"],
                name="bot_interac_tenant__36a7ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interactionfeedback",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="bot_interac_convers_3014fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interactionfeedback",
            index=models.Index(
                fields=["customer", "created_at"], name="bot_interac_custome_c7eb1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentevent",
            index=models.Index(
                fields=["tenant", "created_at"], name="intent_even_tenant__cf56ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentevent",
            index=models.Index(
                fields=["tenant", "intent_name", "created_at"],
                name="intent_even_tenant__f3ba44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intentevent",
            index=models.Index(
                fields=["tenant", "confidence_score"],
                name="intent_even_tenant__0b34e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intentevent",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="intent_even_convers_716fb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intentevent",
            index=models.Index(
                fields=["conversation", "intent_name"],
                name="intent_even_convers_038bef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intentclassificationlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="bot_intent__tenant__d858f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentclassificationlog",
            index=models.Index(
                fields=["tenant", "intent_name"], name="bot_intent__tenant__6840a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentclassificationlog",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="bot_intent__convers_46b3d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intentclassificationlog",
            index=models.Index(
                fields=["model_used", "created_at"],
                name="bot_intent__model_u_09d862_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="humancorrection",
            index=models.Index(
                fields=["tenant", "created_at"], name="bot_human_c_tenant__aa6195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humancorrection",
            index=models.Index(
                fields=["tenant", "approved_for_training", "created_at"],
                name="bot_human_c_tenant__0dab13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="humancorrection",
            index=models.Index(
                fields=["tenant", "correction_category", "created_at"],
                name="bot_human_c_tenant__64984f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="humancorrection",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="bot_human_c_convers_2b622b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["tenant", "is_active", "updated_at"],
                name="conversatio_tenant__f3a604_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["tenant", "customer", "is_active"],
                name="conversatio_tenant__94584d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["conversation", "is_active"],
                name="conversatio_convers_f7cfb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["last_request_id"], name="conversatio_last_re_cadccd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationcontext",
            index=models.Index(
                fields=["conversation", "last_interaction"],
                name="conversatio_convers_22a009_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationcontext",
            index=models.Index(
                fields=["context_expires_at"], name="conversatio_context_911bbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="browsesession",
            index=models.Index(
                fields=["tenant", "conversation", "is_active"],
                name="bot_browse__tenant__84e89d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="browsesession",
            index=models.Index(
                fields=["expires_at"], name="bot_browse__expires_f0bfd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentinteraction",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="agent_inter_convers_75d4bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentinteraction",
            index=models.Index(
                fields=["model_used", "created_at"],
                name="agent_inter_model_u_c7cb3f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentinteraction",
            index=models.Index(
                fields=["confidence_score"], name="agent_inter_confide_ba4b58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentinteraction",
            index=models.Index(
                fields=["handoff_triggered", "created_at"],
                name="agent_inter_handoff_87f849_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentinteraction",
            index=models.Index(
                fields=["message_type", "created_at"],
                name="agent_inter_message_7e1875_idx",
            ),
        ),
    ]
