# Generated by Django 4.2.11 on 2025-11-14 14:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('catalog', '0001_initial'),
        ('messaging', '0004_add_message_campaign'),
        ('bot', '0004_add_knowledge_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('current_topic', models.CharField(blank=True, help_text="Current topic being discussed (e.g., 'product_inquiry', 'booking_appointment')", max_length=100)),
                ('pending_action', models.CharField(blank=True, help_text="Pending action waiting for customer input (e.g., 'awaiting_date_selection')", max_length=100)),
                ('extracted_entities', models.JSONField(blank=True, default=dict, help_text="Extracted entities from conversation (e.g., {'product_name': 'Blue Shirt', 'size': 'L'})")),
                ('conversation_summary', models.TextField(blank=True, help_text='AI-generated summary of conversation history for context window management')),
                ('key_facts', models.JSONField(blank=True, default=list, help_text="List of key facts to remember (e.g., ['Customer prefers blue', 'Budget is $50'])")),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Timestamp of last interaction (auto-updated)')),
                ('context_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When this context expires (null = never expires)', null=True)),
                ('conversation', models.OneToOneField(help_text='Conversation this context belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='context', to='messaging.conversation')),
                ('last_product_viewed', models.ForeignKey(blank=True, help_text='Last product the customer viewed or inquired about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_views', to='catalog.product')),
                ('last_service_viewed', models.ForeignKey(blank=True, help_text='Last service the customer viewed or inquired about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_views', to='services.service')),
            ],
            options={
                'verbose_name': 'Conversation Context',
                'verbose_name_plural': 'Conversation Contexts',
                'db_table': 'conversation_contexts',
                'indexes': [models.Index(fields=['conversation', 'last_interaction'], name='conversatio_convers_22a009_idx'), models.Index(fields=['context_expires_at'], name='conversatio_context_911bbc_idx')],
            },
        ),
    ]
