# Generated by Django 4.2.11 on 2025-11-15 03:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_add_message_queue'),
        ('bot', '0005_add_conversation_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('customer_message', models.TextField(help_text='Original customer message text')),
                ('detected_intents', models.JSONField(blank=True, default=list, help_text='List of detected intents with confidence scores')),
                ('model_used', models.CharField(db_index=True, help_text="LLM model used for this interaction (e.g., 'gpt-4o', 'o1-preview')", max_length=50)),
                ('context_size', models.IntegerField(default=0, help_text='Size of context provided to the model in tokens')),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Time taken to process and generate response in milliseconds')),
                ('agent_response', models.TextField(help_text='Generated agent response text')),
                ('confidence_score', models.FloatField(db_index=True, help_text='Confidence score for the response (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('handoff_triggered', models.BooleanField(db_index=True, default=False, help_text='Whether this interaction triggered a handoff to human agent')),
                ('handoff_reason', models.CharField(blank=True, help_text="Reason for handoff (e.g., 'low_confidence', 'explicit_request', 'restricted_topic')", max_length=100)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('button', 'Button'), ('list', 'List'), ('media', 'Media')], db_index=True, default='text', help_text='Type of message sent to customer', max_length=20)),
                ('token_usage', models.JSONField(blank=True, default=dict, help_text="Token usage breakdown (e.g., {'prompt_tokens': 100, 'completion_tokens': 50, 'total_tokens': 150})")),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD for this interaction', max_digits=10)),
                ('conversation', models.ForeignKey(help_text='Conversation this interaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agent_interactions', to='messaging.conversation')),
            ],
            options={
                'verbose_name': 'Agent Interaction',
                'verbose_name_plural': 'Agent Interactions',
                'db_table': 'agent_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='agent_inter_convers_75d4bc_idx'), models.Index(fields=['model_used', 'created_at'], name='agent_inter_model_u_c7cb3f_idx'), models.Index(fields=['confidence_score'], name='agent_inter_confide_ba4b58_idx'), models.Index(fields=['handoff_triggered', 'created_at'], name='agent_inter_handoff_87f849_idx'), models.Index(fields=['message_type', 'created_at'], name='agent_inter_message_7e1875_idx')],
            },
        ),
    ]
