# Generated by Django 4.2.11 on 2025-11-18 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_add_input_length_limits'),
        ('tenants', '0012_add_together_ai_configuration'),
        ('bot', '0006_add_agent_interaction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('catalog_type', models.CharField(choices=[('products', 'Products'), ('services', 'Services')], help_text='Type of catalog being browsed', max_length=20)),
                ('current_page', models.IntegerField(default=1, help_text='Current page number (1-indexed)')),
                ('items_per_page', models.IntegerField(default=5, help_text='Number of items per page')),
                ('total_items', models.IntegerField(help_text='Total number of items in result set')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters (category, price range, etc.)')),
                ('search_query', models.TextField(blank=True, help_text='Search query if applicable')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether session is still active')),
                ('expires_at', models.DateTimeField(help_text='When session expires (10 minutes from last activity)')),
                ('conversation', models.ForeignKey(help_text='Conversation this browse session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='browse_sessions', to='messaging.conversation')),
                ('tenant', models.ForeignKey(help_text='Tenant this browse session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='browse_sessions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Browse Session',
                'verbose_name_plural': 'Browse Sessions',
                'db_table': 'bot_browse_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'conversation', 'is_active'], name='bot_browse__tenant__84e89d_idx'), models.Index(fields=['expires_at'], name='bot_browse__expires_f0bfd7_idx')],
            },
        ),
    ]
