# Generated by Django 4.2.11 on 2025-11-18 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('messaging', '0008_add_input_length_limits'),
        ('bot', '0007_add_browse_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('context_id', models.CharField(help_text='Unique identifier for this context', max_length=50)),
                ('list_type', models.CharField(choices=[('products', 'Products'), ('services', 'Services'), ('appointments', 'Appointments'), ('orders', 'Orders')], help_text='Type of items in the list', max_length=20)),
                ('items', models.JSONField(help_text='List of items with IDs and display info')),
                ('expires_at', models.DateTimeField(help_text='When context expires (5 minutes from creation)')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_contexts', to='messaging.conversation')),
            ],
            options={
                'verbose_name': 'Reference Context',
                'verbose_name_plural': 'Reference Contexts',
                'db_table': 'bot_reference_contexts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'expires_at'], name='bot_referen_convers_c631ec_idx'), models.Index(fields=['context_id'], name='bot_referen_context_b126ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('key_features', models.JSONField(default=list, help_text='List of key product features')),
                ('use_cases', models.JSONField(default=list, help_text='Common use cases for this product')),
                ('target_audience', models.JSONField(default=list, help_text='Target customer segments')),
                ('embedding', models.JSONField(blank=True, help_text='Semantic embedding vector for similarity search', null=True)),
                ('summary', models.TextField(help_text='AI-generated product summary')),
                ('ai_categories', models.JSONField(default=list, help_text='AI-inferred categories beyond formal taxonomy')),
                ('ai_tags', models.JSONField(default=list, help_text='AI-generated tags for search and matching')),
                ('analyzed_at', models.DateTimeField(auto_now=True, help_text='When analysis was last updated')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Analysis',
                'verbose_name_plural': 'Product Analyses',
                'db_table': 'bot_product_analyses',
                'indexes': [models.Index(fields=['product'], name='bot_product_product_8d47a8_idx'), models.Index(fields=['analyzed_at'], name='bot_product_analyze_c6b1ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='LanguagePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('primary_language', models.CharField(default='en', help_text='Primary language code (en, sw, mixed)', max_length=10)),
                ('language_usage', models.JSONField(default=dict, help_text='Usage statistics per language')),
                ('common_phrases', models.JSONField(default=list, help_text='Commonly used phrases by this customer')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to='messaging.conversation')),
            ],
            options={
                'verbose_name': 'Language Preference',
                'verbose_name_plural': 'Language Preferences',
                'db_table': 'bot_language_preferences',
                'indexes': [models.Index(fields=['conversation'], name='bot_languag_convers_923042_idx')],
            },
        ),
    ]
