# Generated by Django 4.2.11 on 2025-11-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_add_advanced_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationcontext',
            name='clarification_attempts',
            field=models.IntegerField(default=0, help_text='Number of clarification attempts made before handoff'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='shopping_cart',
            field=models.JSONField(blank=True, default=dict, help_text='Shopping cart for multi-item purchases'),
        ),
    ]
