# Generated by Django 4.2.11 on 2025-11-18 13:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_add_input_length_limits'),
        ('tenants', '0012_add_together_ai_configuration'),
        ('bot', '0009_add_context_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'Text')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_progress', models.IntegerField(default=0, help_text='Processing progress percentage (0-100)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('chunk_count', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bot_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGRetrievalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('query', models.TextField()),
                ('source', models.CharField(choices=[('document', 'Document'), ('database', 'Database'), ('internet', 'Internet')], max_length=20)),
                ('result_count', models.IntegerField()),
                ('results', models.JSONField(help_text='Retrieved results with scores')),
                ('retrieval_time_ms', models.IntegerField(help_text='Time taken in milliseconds')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('embedding_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_logs', to='messaging.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_logs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bot_rag_retrieval_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='bot_rag_ret_tenant__f5cbc7_idx'), models.Index(fields=['conversation', 'created_at'], name='bot_rag_ret_convers_5eb8b6_idx'), models.Index(fields=['source', 'success'], name='bot_rag_ret_source_289f90_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternetSearchCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('query', models.CharField(max_length=500)),
                ('query_hash', models.CharField(db_index=True, help_text='Hash of query for fast lookup', max_length=64)),
                ('results', models.JSONField(help_text='Cached search results')),
                ('result_count', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_cache', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bot_internet_search_cache',
                'indexes': [models.Index(fields=['tenant', 'query_hash'], name='bot_interne_tenant__af3b3f_idx'), models.Index(fields=['expires_at'], name='bot_interne_expires_17d09b_idx')],
                'unique_together': {('tenant', 'query_hash')},
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('chunk_index', models.IntegerField(help_text='Position of chunk in document')),
                ('content', models.TextField()),
                ('token_count', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('vector_id', models.CharField(help_text='ID in vector store', max_length=255, unique=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bot.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'bot_document_chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['tenant', 'document'], name='bot_documen_tenant__d5e4a8_idx'), models.Index(fields=['document', 'chunk_index'], name='bot_documen_documen_dfcccc_idx'), models.Index(fields=['vector_id'], name='bot_documen_vector__3774df_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='bot_documen_tenant__b7cad6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'created_at'], name='bot_documen_tenant__89583d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='bot_documen_status_a177a7_idx'),
        ),
    ]
