# Generated by Django 4.2.11 on 2025-11-18 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_add_rag_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='agent_can_do',
            field=models.TextField(blank=True, help_text='Explicit list of what the agent CAN do (for prompt engineering)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='agent_cannot_do',
            field=models.TextField(blank=True, help_text='Explicit list of what the agent CANNOT do (for prompt engineering)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-small', help_text='Embedding model for semantic search', max_length=50),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_database_retrieval',
            field=models.BooleanField(default=True, help_text='Enable retrieval from database (products, services, orders)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_document_retrieval',
            field=models.BooleanField(default=False, help_text='Enable retrieval from uploaded documents'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_internet_enrichment',
            field=models.BooleanField(default=False, help_text='Enable internet search for product enrichment'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_source_attribution',
            field=models.BooleanField(default=True, help_text='Include source citations in responses'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='keyword_search_weight',
            field=models.FloatField(default=0.3, help_text='Weight for keyword search in hybrid search (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='max_database_results',
            field=models.IntegerField(default=5, help_text='Maximum number of database results to retrieve', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='max_document_results',
            field=models.IntegerField(default=3, help_text='Maximum number of document chunks to retrieve', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='max_internet_results',
            field=models.IntegerField(default=2, help_text='Maximum number of internet search results', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='semantic_search_weight',
            field=models.FloatField(default=0.7, help_text='Weight for semantic search in hybrid search (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
