# Generated by Django 4.2.11 on 2025-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_agent_config_feedback'),
    ]

    operations = [
        # Fix ProviderUsage soft delete field
        migrations.RemoveField(
            model_name='providerusage',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='providerusage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True),
        ),
        # Fix ProviderDailySummary soft delete field
        migrations.RemoveField(
            model_name='providerdailysummary',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='providerdailysummary',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True),
        ),
    ]
