# Generated by Django 4.2.11 on 2025-11-20 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_fix_feedback_models_basemodel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='humancorrection',
            new_name='bot_human_c_tenant__aa6195_idx',
            old_name='bot_humanc_tenant__created_idx',
        ),
        migrations.RenameIndex(
            model_name='humancorrection',
            new_name='bot_human_c_tenant__0dab13_idx',
            old_name='bot_humanc_tenant__approved_idx',
        ),
        migrations.RenameIndex(
            model_name='humancorrection',
            new_name='bot_human_c_tenant__64984f_idx',
            old_name='bot_humanc_tenant__category_idx',
        ),
        migrations.RenameIndex(
            model_name='humancorrection',
            new_name='bot_human_c_convers_2b622b_idx',
            old_name='bot_humanc_convers_created_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionfeedback',
            new_name='bot_interac_tenant__48f6fa_idx',
            old_name='bot_interac_tenant__created_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionfeedback',
            new_name='bot_interac_tenant__36a7ca_idx',
            old_name='bot_interac_tenant__rating_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionfeedback',
            new_name='bot_interac_convers_3014fa_idx',
            old_name='bot_interac_convers_created_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionfeedback',
            new_name='bot_interac_custome_c7eb1f_idx',
            old_name='bot_interac_custome_created_idx',
        ),
        migrations.RenameIndex(
            model_name='providerdailysummary',
            new_name='bot_provide_tenant__db7657_idx',
            old_name='bot_provide_tenant__date_idx',
        ),
        migrations.RenameIndex(
            model_name='providerdailysummary',
            new_name='bot_provide_tenant__0f20f3_idx',
            old_name='bot_provide_tenant__provider_date_idx',
        ),
        migrations.RenameIndex(
            model_name='providerusage',
            new_name='bot_provide_tenant__b3c9ab_idx',
            old_name='bot_provide_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='providerusage',
            new_name='bot_provide_tenant__3099e6_idx',
            old_name='bot_provide_tenant__provider_idx',
        ),
        migrations.RenameIndex(
            model_name='providerusage',
            new_name='bot_provide_tenant__e0219d_idx',
            old_name='bot_provide_tenant__model_idx',
        ),
        migrations.RenameIndex(
            model_name='providerusage',
            new_name='bot_provide_convers_642bc4_idx',
            old_name='bot_provide_convers_idx',
        ),
        migrations.AlterField(
            model_name='humancorrection',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this correction was approved', null=True),
        ),
        migrations.AlterField(
            model_name='humancorrection',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Quality rating of the correction (0-5)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
