# Generated by Django 4.2.11 on 2025-11-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_rename_bot_humanc_tenant__created_idx_bot_human_c_tenant__aa6195_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='custom_bot_greeting',
            field=models.TextField(blank=True, help_text='Custom greeting message for first contact (overrides default)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='use_business_name_as_identity',
            field=models.BooleanField(default=True, help_text="Use tenant's business name in bot identity"),
        ),
    ]
