# Generated by Django 4.2.11 on 2025-11-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_add_branded_persona_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_grounded_validation',
            field=models.BooleanField(default=True, help_text='Enable validation that responses are grounded in actual data (prevents hallucinations)'),
        ),
    ]
