# Generated by Django 4.2.11 on 2025-11-20 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_add_input_length_limits'),
        ('bot', '0023_add_grounded_validation_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_immediate_product_display',
            field=models.BooleanField(default=True, help_text='Enable immediate product display without category narrowing'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_message_harmonization',
            field=models.BooleanField(default=True, help_text='Enable message harmonization to combine rapid-fire messages'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_reference_resolution',
            field=models.BooleanField(default=True, help_text="Enable resolution of positional references like '1', 'first', 'last'"),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='harmonization_wait_seconds',
            field=models.IntegerField(default=3, help_text='Seconds to wait before processing harmonized messages (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='max_products_to_show',
            field=models.IntegerField(default=5, help_text='Maximum number of products to show immediately (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='language_locked',
            field=models.BooleanField(default=False, help_text='Whether language preference is locked for this conversation'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_message_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last message received (for harmonization timing)', null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='message_buffer',
            field=models.JSONField(blank=True, default=list, help_text='Buffer for rapid messages awaiting harmonization'),
        ),
        migrations.CreateModel(
            name='MessageHarmonizationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('message_ids', models.JSONField(help_text='List of message IDs that were combined')),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages combined')),
                ('combined_text', models.TextField(help_text='Combined text from all messages')),
                ('wait_time_ms', models.IntegerField(help_text='Time waited before processing in milliseconds')),
                ('first_message_at', models.DateTimeField(help_text='Timestamp of first message in burst')),
                ('last_message_at', models.DateTimeField(help_text='Timestamp of last message in burst')),
                ('response_generated', models.TextField(help_text='Generated response to harmonized messages')),
                ('response_time_ms', models.IntegerField(default=0, help_text='Time taken to generate response in milliseconds')),
                ('typing_indicator_shown', models.BooleanField(default=False, help_text='Whether typing indicator was shown during wait')),
                ('success', models.BooleanField(default=True, help_text='Whether harmonization was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if harmonization failed')),
                ('conversation', models.ForeignKey(help_text='Conversation this harmonization belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='harmonization_logs', to='messaging.conversation')),
            ],
            options={
                'verbose_name': 'Message Harmonization Log',
                'verbose_name_plural': 'Message Harmonization Logs',
                'db_table': 'bot_message_harmonization_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='bot_message_convers_677629_idx'), models.Index(fields=['conversation', 'success'], name='bot_message_convers_b134a9_idx'), models.Index(fields=['created_at'], name='bot_message_created_e23de9_idx')],
            },
        ),
    ]
