# Generated by Django 4.2.11 on 2025-11-21 07:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_add_sales_orchestration_models'),
        ('services', '0001_initial'),
        ('tenants', '0014_merge_20251119_1633'),
        ('orders', '0001_initial'),
        ('bot', '0024_add_ux_enhancement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='business_hours_end',
            field=models.TimeField(default='20:00:00', help_text='Business hours end time'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='business_hours_start',
            field=models.TimeField(default='08:00:00', help_text='Business hours start time'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_card_payments',
            field=models.BooleanField(default=True, help_text='Enable card payments (Paystack/Stripe/Pesapal)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_mpesa_stk',
            field=models.BooleanField(default=True, help_text='Enable M-Pesa STK push payments'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_rule_based_intent',
            field=models.BooleanField(default=True, help_text='Enable rule-based intent classification (faster, cheaper)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='intent_confidence_threshold',
            field=models.FloatField(default=0.65, help_text='Minimum confidence threshold for intent classification (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='llm_budget_exceeded_action',
            field=models.CharField(choices=[('fallback', 'Fallback to rules'), ('throttle', 'Throttle usage'), ('stop', 'Stop LLM usage')], default='fallback', help_text='Action to take when LLM budget is exceeded', max_length=20),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='monthly_llm_budget_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Monthly LLM budget in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, help_text='Quiet hours end time', null=True),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, help_text='Quiet hours start time (no automated messages)', null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='awaiting_response',
            field=models.BooleanField(default=False, help_text='Whether bot is awaiting a specific response from customer'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='current_flow',
            field=models.CharField(blank=True, help_text="Current flow state (e.g., 'browsing_products', 'checkout', 'booking')", max_length=50),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='detected_language',
            field=models.JSONField(blank=True, default=list, help_text="Detected languages (e.g., ['en'], ['sw'], ['sheng'])"),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_menu',
            field=models.JSONField(blank=True, default=dict, help_text="Last displayed menu for reference resolution (e.g., {'type': 'products', 'items': [...]})"),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_menu_timestamp',
            field=models.DateTimeField(blank=True, help_text='When last_menu was created (for expiration checking)', null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_question',
            field=models.TextField(blank=True, help_text='Last question asked by bot (for context)'),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='KES', help_text='Currency code (e.g., KES, USD)', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa_stk', 'M-Pesa STK Push'), ('mpesa_manual', 'M-Pesa Manual'), ('paystack', 'Paystack'), ('stripe', 'Stripe'), ('pesapal', 'Pesapal')], db_index=True, help_text='Payment method used', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING_REVIEW', 'Pending Review')], db_index=True, default='PENDING', help_text='Payment status', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text="Provider's reference/transaction ID", max_length=255)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text="Provider's initial response")),
                ('callback_received_at', models.DateTimeField(blank=True, help_text='When callback was received', null=True)),
                ('callback_data', models.JSONField(blank=True, default=dict, help_text='Callback data from provider')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for payment (M-Pesa)', max_length=20)),
                ('payment_link', models.URLField(blank=True, help_text='Payment link sent to customer (card payments)', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('appointment', models.ForeignKey(blank=True, help_text='Appointment being paid for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='services.appointment')),
                ('customer', models.ForeignKey(help_text='Customer making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='tenants.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Order being paid for (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='orders.order')),
                ('tenant', models.ForeignKey(help_text='Tenant this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'db_table': 'bot_payment_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='bot_payment_tenant__d0d832_idx'), models.Index(fields=['tenant', 'status', 'created_at'], name='bot_payment_tenant__de376e_idx'), models.Index(fields=['customer', 'created_at'], name='bot_payment_custome_ffc57d_idx'), models.Index(fields=['order', 'created_at'], name='bot_payment_order_i_515e1d_idx'), models.Index(fields=['appointment', 'created_at'], name='bot_payment_appoint_58216b_idx'), models.Index(fields=['provider_reference'], name='bot_payment_provide_b687b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('model_name', models.CharField(db_index=True, help_text="LLM model name (e.g., 'gpt-4o-mini', 'qwen-2.5-7b', 'gemini-flash')", max_length=100)),
                ('task_type', models.CharField(db_index=True, help_text="Task type (e.g., 'intent_classification', 'slot_extraction', 'rag_answer')", max_length=50)),
                ('input_tokens', models.IntegerField(help_text='Number of input tokens')),
                ('output_tokens', models.IntegerField(help_text='Number of output tokens')),
                ('total_tokens', models.IntegerField(help_text='Total tokens (input + output)')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, help_text='Estimated cost in USD', max_digits=10)),
                ('prompt_template', models.TextField(blank=True, help_text='Prompt template used (for debugging)')),
                ('response_preview', models.TextField(blank=True, help_text='First 500 chars of response (for debugging)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (temperature, max_tokens, etc.)')),
                ('conversation', models.ForeignKey(blank=True, help_text='Conversation this usage belongs to (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage_logs', to='messaging.conversation')),
                ('tenant', models.ForeignKey(help_text='Tenant this usage belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'db_table': 'bot_llm_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='bot_llm_usa_tenant__5cf903_idx'), models.Index(fields=['tenant', 'model_name', 'created_at'], name='bot_llm_usa_tenant__fc80d7_idx'), models.Index(fields=['tenant', 'task_type', 'created_at'], name='bot_llm_usa_tenant__c8d3e7_idx'), models.Index(fields=['conversation', 'created_at'], name='bot_llm_usa_convers_c3ac03_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntentClassificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('detected_intent', models.CharField(db_index=True, help_text='Detected intent (e.g., BROWSE_PRODUCTS, PLACE_ORDER)', max_length=50)),
                ('confidence', models.FloatField(help_text='Confidence score from 0.0 to 1.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('method', models.CharField(choices=[('rule', 'Rule-based'), ('llm', 'LLM-based'), ('context', 'Context-based')], db_index=True, help_text='Classification method used', max_length=20)),
                ('extracted_slots', models.JSONField(blank=True, default=dict, help_text="Extracted slots/entities (e.g., {'category': 'shoes', 'budget': 5000})")),
                ('detected_language', models.JSONField(blank=True, default=list, help_text="Detected languages (e.g., ['en'], ['sw'], ['en', 'sw'])")),
                ('classification_time_ms', models.IntegerField(help_text='Time taken to classify in milliseconds')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (matched_patterns, llm_model, etc.)')),
                ('conversation', models.ForeignKey(help_text='Conversation this classification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='intent_classification_logs', to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, help_text='Message that was classified', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intent_classification_logs', to='messaging.message')),
                ('tenant', models.ForeignKey(help_text='Tenant this classification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='intent_classification_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Intent Classification Log',
                'verbose_name_plural': 'Intent Classification Logs',
                'db_table': 'bot_intent_classification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='bot_intent__tenant__d858f5_idx'), models.Index(fields=['tenant', 'detected_intent', 'created_at'], name='bot_intent__tenant__4d0f31_idx'), models.Index(fields=['tenant', 'method', 'created_at'], name='bot_intent__tenant__12793c_idx'), models.Index(fields=['conversation', 'created_at'], name='bot_intent__convers_46b3d9_idx')],
            },
        ),
    ]
