# Generated by Django 4.2.11 on 2025-11-21 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_add_sales_orchestration_models'),
        ('tenants', '0014_merge_20251119_1633'),
        ('catalog', '0001_initial'),
        ('orders', '0002_add_conversation_flow_fixes_models'),
        ('bot', '0025_add_sales_orchestration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_disclaimer_removal',
            field=models.BooleanField(default=True, help_text='Enable disclaimer removal to remove confidence-undermining phrases'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_echo_prevention',
            field=models.BooleanField(default=True, help_text='Enable echo prevention filter to remove customer message echoes'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='enable_quick_checkout',
            field=models.BooleanField(default=True, help_text='Enable quick checkout flow (≤3 messages from selection to payment)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='fallback_to_text_on_error',
            field=models.BooleanField(default=True, help_text='Fall back to text messages if interactive message API fails'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='force_interactive_messages',
            field=models.BooleanField(default=True, help_text='Force use of WhatsApp interactive elements (lists, buttons)'),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='max_checkout_messages',
            field=models.IntegerField(default=3, help_text='Maximum messages allowed in checkout flow (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='max_response_sentences',
            field=models.IntegerField(default=3, help_text='Maximum number of sentences in bot responses (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='checkout_state',
            field=models.CharField(default='browsing', help_text='Current checkout state (browsing, product_selected, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='current_session_start',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Start time of current conversation session', null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_bot_message',
            field=models.TextField(blank=True, help_text='Last message sent by bot (for echo prevention)'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='last_customer_message',
            field=models.TextField(blank=True, help_text='Last message sent by customer (for echo prevention)'),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='selected_product_id',
            field=models.UUIDField(blank=True, help_text='ID of currently selected product in checkout', null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='selected_quantity',
            field=models.IntegerField(blank=True, help_text='Selected quantity for checkout', null=True),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='session_message_count',
            field=models.IntegerField(default=0, help_text='Number of messages in current session'),
        ),
        migrations.CreateModel(
            name='ResponseValidationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('had_echo', models.BooleanField(db_index=True, default=False, help_text='Whether response contained customer message echo')),
                ('had_disclaimer', models.BooleanField(db_index=True, default=False, help_text='Whether response contained disclaimer phrases')),
                ('exceeded_length', models.BooleanField(db_index=True, default=False, help_text='Whether response exceeded maximum length')),
                ('missing_cta', models.BooleanField(db_index=True, default=False, help_text='Whether response was missing call-to-action')),
                ('original_response', models.TextField(help_text='Original response before validation/cleaning')),
                ('cleaned_response', models.TextField(help_text='Cleaned response after validation/cleaning')),
                ('validation_time_ms', models.IntegerField(default=0, help_text='Time taken to validate in milliseconds')),
                ('issues_found', models.JSONField(blank=True, default=list, help_text='List of specific issues found during validation')),
                ('conversation', models.ForeignKey(help_text='Conversation this validation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='messaging.conversation')),
                ('message', models.ForeignKey(blank=True, help_text='Message that was validated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='messaging.message')),
            ],
            options={
                'verbose_name': 'Response Validation Log',
                'verbose_name_plural': 'Response Validation Logs',
                'db_table': 'bot_response_validation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='bot_respons_convers_29341c_idx'), models.Index(fields=['conversation', 'had_echo'], name='bot_respons_convers_1148d1_idx'), models.Index(fields=['conversation', 'had_disclaimer'], name='bot_respons_convers_e1fefe_idx'), models.Index(fields=['created_at'], name='bot_respons_created_c49019_idx')],
            },
        ),
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('state', models.CharField(choices=[('browsing', 'Browsing'), ('product_selected', 'Product Selected'), ('quantity_confirmed', 'Quantity Confirmed'), ('payment_method_selected', 'Payment Method Selected'), ('payment_initiated', 'Payment Initiated'), ('payment_confirmed', 'Payment Confirmed'), ('order_complete', 'Order Complete')], db_index=True, default='browsing', help_text='Current checkout state', max_length=50)),
                ('quantity', models.IntegerField(blank=True, help_text='Selected quantity', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When checkout session started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When checkout was completed', null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, help_text='When checkout was abandoned', null=True)),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages in this checkout session')),
                ('conversation', models.ForeignKey(help_text='Conversation this checkout session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='messaging.conversation')),
                ('customer', models.ForeignKey(help_text='Customer in this checkout session', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='tenants.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Created order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='orders.order')),
                ('payment_request', models.ForeignKey(blank=True, help_text='Payment request for this checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='bot.paymentrequest')),
                ('selected_product', models.ForeignKey(blank=True, help_text='Selected product for purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='catalog.product')),
                ('tenant', models.ForeignKey(help_text='Tenant this checkout session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Checkout Session',
                'verbose_name_plural': 'Checkout Sessions',
                'db_table': 'bot_checkout_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['tenant', 'state', 'started_at'], name='bot_checkou_tenant__858685_idx'), models.Index(fields=['conversation', 'state'], name='bot_checkou_convers_eb15ad_idx'), models.Index(fields=['conversation', 'started_at'], name='bot_checkou_convers_14f70a_idx'), models.Index(fields=['state', 'started_at'], name='bot_checkou_state_a8a171_idx')],
            },
        ),
    ]
