# Generated by Django 4.2.11 on 2025-12-20 06:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_add_sales_orchestration_models'),
        ('tenants', '0016_customer_consent_flags_customer_language_preference_and_more'),
        ('bot', '0026_add_conversation_flow_fixes_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('state_data', models.JSONField(help_text='Serialized ConversationState as JSON')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this session is currently active')),
                ('last_request_id', models.CharField(help_text='ID of the last processed request', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional session metadata')),
                ('conversation', models.OneToOneField(help_text='Conversation this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='session', to='messaging.conversation')),
                ('customer', models.ForeignKey(help_text='Customer this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to='tenants.customer')),
                ('tenant', models.ForeignKey(help_text='Tenant this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
                'db_table': 'conversation_sessions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'updated_at'], name='conversatio_tenant__f3a604_idx'), models.Index(fields=['tenant', 'customer', 'is_active'], name='conversatio_tenant__94584d_idx'), models.Index(fields=['conversation', 'is_active'], name='conversatio_convers_f7cfb9_idx'), models.Index(fields=['last_request_id'], name='conversatio_last_re_cadccd_idx')],
            },
        ),
    ]
