# Generated by Django 4.2.11 on 2025-12-20 06:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_customer_consent_flags_customer_language_preference_and_more'),
        ('bot', '0027_add_conversation_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('title', models.CharField(help_text='Document title or filename', max_length=255)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('txt', 'Text File'), ('faq', 'FAQ Entry'), ('policy', 'Policy Document'), ('manual', 'User Manual')], db_index=True, help_text='Type of document', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of the document content')),
                ('file_path', models.CharField(help_text='Path to the stored file', max_length=500)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of file content for deduplication', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Processing status', max_length=20)),
                ('processing_progress', models.PositiveSmallIntegerField(default=0, help_text='Processing progress percentage (0-100)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('chunk_count', models.PositiveIntegerField(default=0, help_text='Number of chunks created from this document')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total number of tokens in all chunks')),
                ('embedding_model', models.CharField(default='text-embedding-3-small', help_text='Model used for generating embeddings', max_length=100)),
                ('vector_namespace', models.CharField(db_index=True, help_text='Vector database namespace (tenant-scoped)', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization and search')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (author, source, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the document was uploaded')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing was completed', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this document is active and should be used for retrieval')),
                ('tenant', models.ForeignKey(help_text='Tenant this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_documents', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Document',
                'verbose_name_plural': 'Tenant Documents',
                'db_table': 'bot_tenant_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantDocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the record was soft deleted', null=True)),
                ('chunk_index', models.PositiveIntegerField(help_text='Position of chunk within document (0-based)')),
                ('content', models.TextField(help_text='Text content of the chunk')),
                ('token_count', models.PositiveIntegerField(help_text='Number of tokens in this chunk')),
                ('page_number', models.PositiveIntegerField(blank=True, help_text='Page number in source document (if applicable)', null=True)),
                ('section_title', models.CharField(blank=True, help_text='Section or heading title (if applicable)', max_length=255)),
                ('vector_id', models.CharField(db_index=True, help_text='Unique ID in vector database', max_length=255, unique=True)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', help_text='Model used for generating embedding', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional chunk metadata')),
                ('document', models.ForeignKey(help_text='Document this chunk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bot.tenantdocument')),
            ],
            options={
                'verbose_name': 'Tenant Document Chunk',
                'verbose_name_plural': 'Tenant Document Chunks',
                'db_table': 'bot_tenant_document_chunks',
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='bot_tenant__documen_bc4aa8_idx'), models.Index(fields=['vector_id'], name='bot_tenant__vector__098c3b_idx'), models.Index(fields=['document', 'page_number'], name='bot_tenant__documen_09f0eb_idx')],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['tenant', 'is_active', 'status'], name='bot_tenant__tenant__d9adcb_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['tenant', 'document_type', 'is_active'], name='bot_tenant__tenant__bb5472_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['tenant', 'uploaded_at'], name='bot_tenant__tenant__eace49_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['vector_namespace'], name='bot_tenant__vector__de3393_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['file_hash'], name='bot_tenant__file_ha_2b69c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantdocument',
            unique_together={('tenant', 'file_hash')},
        ),
    ]
